### ISSUE TITLE
직렬화 도구

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#10]
이벤트 소싱에서 직렬화는 중요합니다. 이벤트 저장소와 이벤트 발행기를 통해 이벤트의 형식과 정보가 온전히 기록 및 복원되고 발행되어야 합니다. 직렬화 도구 인터페이스와 가장 많이 사용되는 JSON 형식의 구현체를 작성합니다.

**Comment by jaceshim** [comment]
@gyuwon 
java쪽에선 주로 jackson ObjectMapper를 사용합니다

추가적으로 https://github.com/google/gson 나 http://modelmapper.org/ 등을 주로 사용합니다

**Comment by mhyeon-lee** [comment]
@jaceshim 님이 말씀하신대로 주로 jackson 이 주로 사용됩니다.
성능도 gson 보다 좋다는 benchmark 를 봤던거 같습니다.

**Comment by gyuwon** [comment]
@jaceshim @mhyeon-lee 그럼 JSON 직렬화 기능은 jackson을 사용하기로 하고요, 인터페이스 설계가 필요한데 jackson을 이용하면 형 정보는 어떻게 제어되나요?

**Comment by mhyeon-lee** [comment]
Event serialize / deserialize 할때 Event 타입에 대한 값을 말씀하시는거죠?

질문하신 의도와 맞는 답변인지 모르겠지만 아래와 같이 많이 사용합니다.
annotation 이 아닌 programmatic 한 방법은 문서를 좀 찾아봐야겠네요
https://github.com/FasterXML/jackson-annotations#handling-polymorphic-types
http://www.cowtowncoder.com/blog/archives/2010/03/entry_372.html

**Comment by gyuwon** [comment]
직렬화 대상에 매번 직렬화를 위한 코드가 추가되는 것보다 직렬화기(serializer)가 처리하는 방법이 있다면 더 좋을텐데요. jackson 외에 다른 도구들도 한 번 살펴볼 필요가 있겠습니다.

**Comment by enshahar** [comment]
jackson에서도 직렬화기가 알아서 처리해주는  것 같습니다.

```java
package com.enshahar.study;

import java.lang.*;
import com.fasterxml.jackson.databind.ObjectMapper;

class Data {
    Data(String s, int i) { str = s; integer = i; }

    public String str;
    public int integer;
}

class App
{
    public static void main (String[] args) throws java.lang.Exception
    {
        // your code goes here
        Data album = new Data("String",1010);
        ObjectMapper mapper = new ObjectMapper();

        try {
            System.out.println(mapper.writeValueAsString(album));
        } catch(Exception e) {

        }
    }
}
```

실행결과:

```json
{"str":"String","integer":1010}
```

pom.xml

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.enshahar.study</groupId>
  <artifactId>JacksonTest</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>JacksonTest</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.8.8</version>
    </dependency>
    <!--dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.8.8</version>
    </dependency-->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.8.8</version>
    </dependency>
  </dependencies>
</project>
```

**Comment by HomoEfficio** [comment]
안녕하세요. 눈팅으로 배우다가 빨대 한 번 들이대봅니다 ㅋㅋ
Jackson Custom Serializer/Deserializer 인데 혹시 참고가 될까해서요.

http://homoefficio.github.io/2016/11/18/%EC%95%8C%EA%B3%A0%EB%B3%B4%EB%A9%B4-%EB%A7%8C%EB%A7%8C%ED%95%9C-Jackson-Custom-Serialization/

http://homoefficio.github.io/2016/11/19/%EC%A1%B0%EA%B8%88%EC%9D%80-%EC%8B%A0%EA%B2%BD%EC%8D%A8%EC%A4%98%EC%95%BC-%ED%95%98%EB%8A%94-Jackson-Custom-Deserialization/

형 정보는 제가 질문 의도를 맞게 이해한 건지 모르지만, `TypeReference<T>`로 제어합니다.
위의 Deserialization 예제에 있습니다.

**Comment by gyuwon** [comment]
@enshahar 코드와 결과를 보면 JSON이 필드 정보만 가지는데요, 그러면 역직렬화 시 원래의 형식인 `Data`을 잃게되지 않나요?

**Comment by gyuwon** [comment]
@HomoEfficio 도움 감사합니다. 👍 그런데 메시지(명령, 이벤트) 마다 직렬화기를 모두 만들어주는 것은 현실적으로 어려움이 있습니다. 인프라 수준에서 한 번에 처리할 수 있는 방법은 없을까요?

**Comment by jaceshim** [comment]
@gyuwon 직렬화 하는 시점이 event store에 저장 또는 발행 시점이고 이 경우 loom의 추상화 레벨에서 처리 되기때문에(그렇게 구현 하겠죠?)  개발자가 구현시 매번 직렬화 관련 코드를 코딩하지는 않을것 같습니다.

**Comment by gyuwon** [comment]
@jaceshim 맞습니다. 그리고 메시지 수신자가 메시지 뿐 아니라 메시지 직렬화기에 대해서 까지 모두 알아야하는 불편함도 큽니다.

**Comment by jaceshim** [comment]
@gyuwon 직렬화된 메세지가 json type이라면 수신자가 역직열화시에 직렬화기에 대한 고민은 필요 없을것 같습니당~
즉 ObjecMapper든 Gson이든 json type으로 직렬화 된 메세지는 수신자가 알아서 역직렬화기를 선택해서 사용해도 무관하고 다만 수신자는 역직렬화시 사용되는 객체 type은 당연히 알고 있어야 하는거니 큰 불편함은 없을것 같습니다. 저의 토이 프로젝트에서도 보면 특정 도메인에서 발행되는 이벤트 타입을 별도의 jar로 배포해서 발행된 이벤트를 수신하는 타 도메인에서 역직렬화시에 사용하도록 
구성 했었습니당~

**Comment by HomoEfficio** [comment]
Spring의 `ResponseEntity<EventType>` 비슷한 놈을 loom의 추상층에 두면 좋을 것 같습니다. 직렬화도 그 추상층 내부에서 처리되게 할 수 있을 것 같고요.

**Comment by gyuwon** [comment]
@jaceshim 말씀하신 방법은 API를 기반으로 한 분산 시스템의 경우는 별 문제가 없을 수 있습니다. 하지만 메시지 중심(message-driven) 분산 시스템에서는 문제가 생깁니다. 다양한 유형의 메시지(명령과 이벤트)가 메시지 중개자로부터 전달되기 때문에 속성만을 담고있는 JSON 데이터로는 메시지 수신자가 어떤 유형의 메시지인지 알 수 없습니다. API 중심의 분산 시스템은 이벤트 소싱과 잘 어울리지 않습니다.

다음 두 이벤트를 보시죠.

```java
public class UserCreated {
    public UUID userId;
    public String userName;
}

public class UserNameChanged {
    public UUID userId;
    public String userName;
}
```

두 이벤트가 JSON 직렬화 시 속성 값만을 담는다면 메시지 수신자는 메시지의 중요한 정보인 동사를 잃어버립니다.

**Comment by mhyeon-lee** [comment]
Axon framework 에서도 여러 serializer 를 지원했던 기억이 있어서 인터페이스를 찾아봤습니다.
참고해볼만 한거 같습니다.

https://github.com/AxonFramework/AxonFramework/blob/master/core/src/main/java/org/axonframework/serialization/Serializer.java

관련 패키지는 여기
https://github.com/AxonFramework/AxonFramework/tree/master/core/src/main/java/org/axonframework/serialization

**Comment by gyuwon** [comment]
@mhyeon-lee Axon 직렬화기 인터페이스도 결국에는 `T`를 알고있어야 한는 것 아닌가요?

**Comment by mhyeon-lee** [comment]
여기서 T 는 파라미터로 넘기는 Class<T> 와 return 하는 SerializedObject<T> 내부에서 가지고 있을 type(class) 을 컴파일 단계에서 맞추기 위함인거 같습니다.

파라미터와 serializedObject 모두 타입(class) 를 가지고 있어서 event 형을 알 수 있을거 같습니다.
자세히는 보지 않아서 좀 둘러봐야될거 같습니다.

**Comment by jaceshim** [comment]
@gyuwon 규원님 말씀은 직렬화된 매새지에 T 타입에 대한 정보가 포함되어 있어야 수신자가 이게 어떤 타입인지 알수 있다는 말씀이신거죠?

**Comment by gyuwon** [comment]
@jaceshim 네 맞습니다. 메시지 수신자가 개체를 복원하려면 속성 뿐 아니라 형 정보(동사)에 대한 정보를 받아야하죠. 만약 직렬화기에서 처리가 불가능하다면 메시지를 주고 받을 때, 그리고 저장소에 기록하고 복원할 때 항상 동사에 대한 메타데이터를 묶어서 다뤄야 합니다. 그렇게 하면 안되는 것은 아니지만 설계가 복잡해 지기 때문에 가능하면 클라이언트 입장에서 쉬운 방법을 찾아보려는 거에요.

**Comment by jaceshim** [comment]
@gyuwon
아 그 부분 이라면 
기억이 가물가물한데 jackson 에서 사용할수 있는 시리얼라이저 중에 타입을 직렬화 메세지에 포함시키는 시리얼라이저 및 그를 활용하는 디시리얼라이저가 존재했던걸로 기억합니다!

**Comment by mhyeon-lee** [comment]
@jaceshim 저 위에 제가 링크로 남긴 이거 말씀하신건가요?
https://github.com/FasterXML/jackson-annotations#handling-polymorphic-types

그런데 이건 어노테이션 방식이라 이거 외에 Serializer 가 있으면 좋을거 같은데 찾아봐야될거 같습니다.

**Comment by jaceshim** [comment]
@mhyeon-lee
어노테이션 기반은 아니었구요~
Jdk 어쩌구저쩌구 시리얼라이저/디시리얼라이저 로 기억 나는데 지금 외부에 있어서 찾기가 거시기 하네요

**Comment by gyuwon** [comment]
그러면 @jaceshim 님이 조사해주시는 것으로! :)

참고로 직렬화 도구가 그런 지원을 해주면 직렬화기 인터페이스는 이런 식으로 단순해질 수 있습니다.

https://github.com/Reacture/Khala.Messaging/blob/master/source/Khala.Messaging/Messaging/IMessageSerializer.cs

그리고 실질적으로 클라이언트는 직렬화/ 역직렬화 과정에 대해 전혀 관여하지 않고 `Object` 형식의 개체를 전달받아 형 검사를 통해 메시지를 처리할 수 있죠.

**Comment by mhyeon-lee** [comment]
네 제가 한번 찾아보겠습니다.

**Comment by mhyeon-lee** [comment]
음 우선은 @jaceshim 님이 말씀하신 serializer 가 잘 안보이네요.
여건 되실때 한번 찾아봐주세요

만약 없다면, 기본 Serializer 인터페이스는 @gyuwon 님 Khala 프로젝트의 IMessageSerializer 인터페이스 형식을 사용하고 구현체에서 해당 event type 을  serialize 에 포함시키고 deserialize 할 수 있도록 어답터 를 만들어 주면 될거 같습니다

**Comment by jwChung** [comment]
저도 @mhyeon-lee 님 의견처럼 통상의 json serializer에 타입 인식 기능을 직접 구현하는 것도 나쁘지 않다고 생각합니다.

**Comment by mhyeon-lee** [comment]
우선 Object 를 String 으로 Serialize,  String 을 Object 로 Deserialize 하는 직렬화기 인터페이스를 만들어야 겠네요. Khala.Messaging 프로젝트의 IMessageSerializer 를 따와서 아래와 같이 하면 어떨까 합니다.

``` java
package io.loom.message;

public interface MessageSerializer {
    String serialize(Object message);
    Object deserialize(String value);
}
```

**Comment by jaceshim** [comment]
일전에 말씀 드렸던 jackson의 type을 포함하는 직렬화기는  java 기반에서만 사용가능한 직렬화기라서 제외 되어야 할듯합니다. 이 직렬화기를 통해서 직렬화된 메세지는 반드시 해당 type ( Java class ) 로만 역직렬화되어야 하는 문제점이 있습니다. [https://developers.google.com/protocol-buffers/](url) 나 [https://thrift.apache.org/](url) 를 통한 처리도 한가지 방법이 될 수 있을듯 합니다.

**Comment by gyuwon** [comment]
@jaceshim 직렬화 결과가 JSON인데 반드시 Java 클래스로만 역직렬화된다는 것이 이해가 안됩니다. :)

**Comment by jaceshim** [comment]
@gyuwon 
사전에 제가 거론에 직렬화기에 오해가 있었던것 같아요~ 
제가 말씀 드렸던 직렬화기는 json 포맷을 이용하는게 아닙니다. 
제가 이 직렬화기를 거론한 이유는 message에 type을 포함시킬 수 있냐는 이슈에 대해 거론한거구요
만약 범용성을 목적에 두고 json 형식을 사용해야 한다면 해당 직렬화기는 사용할 수 없습니다.

**Comment by gyuwon** [comment]
@jaceshim 저도 한 번 조사해보고 싶은데요, 프로젝트에서 jackson을 사용하려면 어떻게 해야하나요?

**Comment by mhyeon-lee** [comment]
https://github.com/loom/loom-core/pull/43/files 
Jackson/Gson 에서 type 을 포함한 serializing, deserializing option 을 찾아서 여기에 테스트 작성한걸 올려봤습니다.

테스트 하면서 간단한 MessageSerializer 인터페이스도 적용해봤습니다.

**Comment by mhyeon-lee** [comment]
https://github.com/loom/loom-core/pull/47  merge 되면서 이 이슈는 닫겠습니다.

메시지 직렬화기와 관련된 추가 논의는 별도 이슈로 진행하면 되겠습니다
