### ISSUE TITLE
바이너리 배포 프로세스

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#12]
https://github.com/loom/loom-core/issues/2 에 이어서 논의를 이어갑니다.

**Comment by jwChung** [comment]
semver를 사용한 CD(continuous delivery) 제안드립니다.

_병합된 PR이 semver 기준으로 버전 증가에 해당하면 CD를 트리거. 이때 버전정보과 릴리즈노트가 필요함._

CD 트리거는 아래와 같이 git annotation 태그 이용을 제안합니다.

```git
git tag -a 1.0.1 -m 릴리즈노트추가
git push origin 1.0.1
``` 

travis에서 위 방법을 지원할 꺼라고 생각합니다. 구성 방법은 해보질 않아서 잘 모릅니다. -_-;;
