### ISSUE TITLE
이벤트 근원 개체(집합체) 식별자 형식

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#13]
CQRS와 이벤트 소싱, 그리고 비동기 프로세스에서 `UUID`는 식별자로서 특별한 의미가 있습니다. 요청자 입장에서 식별자의 전역 유일성을 보장받고 개체 생성 트랜잭션이 처리되기 전에 요청자가 생성될 개체의 식별자를 알 수 있다는 점이죠. 이것이 보장되지 않으면 비동기 프로세스에서 골치아픈 많은 일들이 벌어집니다. 그래서 CQRS에선 대부분 `UUID(혹은 GUID)`를 식별자로 사용합니다.

반대로 `UUID`를 식별자로 사용할 때 관계형 데이터베이스에서 스키마 설계에 신경쓰지 않으면 성능 이슈가 발생하죠. 이것에 대한 합리적인 해결책은 존재합니다.

http://byterot.blogspot.kr/2013/02/performance-series-guids-vs-identity-rdbms-sql.html

만약 이벤트 근원 개체 식별자를 `UUID`로 제한하면 도구 수준에서 이 성능 이슈 해결책을 제공하기 상대적으로 쉽습니다.([Khala.EventSourcing 프로젝트](https://github.com/Reacture/Khala.EventSourcing/blob/master/source/Khala.EventSourcing.Sql/EventSourcing/Sql/PersistentEvent.cs) 참고)

이벤트 근원 개체 식별자 형식을 `UUID`로 제한할지 열어둘지 여부를 프로젝트 초기에 결정하는 것이 좋겠습니다.

**Comment by mhyeon-lee** [comment]
넵  global 식별성을 보장하기 위해서 uuid 를 id 로 사용하는데에는 동의합니다.
rdbms 의 경우도 varchar 타입으로 uuid 를 저장하면 성능 이슈가 발생하지만 제가 진행하고 있는 프로젝트에서는 binary(16) 으로 저장하여 오히려 더 가볍게 사용하고 있습니다.

https://github.com/loom/loom-core/pull/11/files#diff-24428a175410f47959fd39f0fb842a54R11
여기에서 ID 타입을 UUID 로 고정하지 않고 generics 로 받은거는 entity 를 구현하는 사람에 따라 다른 타입을 식별자로 사용할 수 있게 지원하기 위함입니다.

저는 보통 해당 Aggregate 의 식별자 타입을 별도로 만듭니다. 
예를들어 Issue 에는 IssueId, Order 에는 OrderId 와 같은 식별자를 만들고 내부에 uuid 를 가지는 방식으로 식별자를 사용합니다. 
AggregateRoot 인터페이스에서 ID 타입을 UUID 로 고정하면 이러한 방식의 식별자는 설계할 수 없는 제한이 발생합니다.

**Comment by mhyeon-lee** [comment]
추가로 타입을 별도로 만드는 이유는 식별자로서의 uuid 와 값으로서의 uuid 를 구별하기 위함입니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 관계형 데이터베이스에서 `UUID`의 성능 이슈는 문자열로 저장해서 발생하는 것은 아닙니다. 그리고 문자열로 저장해서도 안되고요. 제가 링크한 문서를 읽어보시면 도움이 되실겁니다.

**Comment by mhyeon-lee** [comment]
네 링크 주신 문서 의견대로  uuid 로 식별자를 사용해야 되는것에는 동의합니다.

타입을 UUID로 고정할 것인지 열어둘 것인지는,  uuid 기반의 custom-type 을 지원할 것인지 안할것인지로 결정하면 되겠군요

**Comment by jwChung** [comment]
@mhyeon-lee 질문 좀 드리겠습니다.

1.
> 추가로 타입을 별도로 만드는 이유는 식별자로서의 uuid 와 값으로서의 uuid 를 구별하기 위함입니다.

식별자로서의 uuid vs 값으로서의 uuid 가 무엇인가요?

2. uuid 기반의 custom-type 지원이 아래와 같은 것인가요? 1번과 연결되는 질문인 것 같은데 이것이 어떤 의미를 가지나요?

```java
public class OrderId {
  public getValue () {  return UUID.randomUUID(); }
}
```

**Comment by mhyeon-lee** [comment]
1. 코드에서 UUID 타입의 어떤 변수나 파라미터 등을 봤을때, 이게 Aggregate 의 ID 를 의미하는건지 단순한 UUID 값을 의미하는건지를 구분하기 위함입니다. 물론 변수명이나 메소드 명을 잘 지음으로써 이해할 수 있게 하는게 더 좋지만 저는 별도 타입을 만드는걸 선호하는편입니다. 

예를 들어 아래 코드와 같은 상황으로 이해하시면 될거 같습니다.

``` java 
void caculate(UUID orderId,  List<UUID> orderItemIds, UUID seed);

void caculate(OrderId orderId, List<OrderItemId> orderItemIds, UUID seed); 
```

2. 네 예제로 만드신것과 비슷합니다.

``` java
public class OrderId {
    private final UUID value;
    public String toString() {
         return value.toString();
    }
```

아래와 같은 경우에 타입 체크가 가능합니다.

``` java
public class Order {
      public void command(OrderItemId orderItemId) {
           // do action
      }
}
```

**Comment by gyuwon** [comment]
`OrderId`와 같은 형식을 사용할 경우 이벤트 저장소는 이를 어떻게 처리해야 할까요?

**Comment by mhyeon-lee** [comment]
그렇네요 결국은 이벤트 저장소에 넣을때는 OrderId 에서 uuid 를 꺼내서 넘겨줘야 겠습니다.
그런데 이렇게 할건지는 구현체 에서 결정할 일인거 같군요
인터페이스에서는 UUID 로 고정하고 Generics 도 제거하겠습니다.

**Comment by mhyeon-lee** [comment]
UUID 타입으로 우선 결정하고 이 이슈는 닫겠습니다
다른 의견있으신 분은 이 이슈를 다시 open 하면 됩니다

**Comment by jaceshim** [comment]
Aggregate의 식별자를 UUID로 고정 하는거에 대해서 이견이 있습니다. Aggregate 식별자가 loom내부적으로만 사용되는 값이라면 문제될게 없지만 이 식별자는 loom을 사용해서 구현되는 영역에도 노출이 되는 값이고 이를 활용해 코드가 구현된다면  loom은 특정 도메인에 의존적인 프레임웤이 아니다 보니 실제 Aggregate 식별자로 UUID가 아닌 다른 type을 사용하고자 하는 이슈는 분명히 발생 할거라 보는데요 어떠신가요?

**Comment by gyuwon** [comment]
@jaceshim 이벤트 소싱(혹은 CQRS)에서 도메인 개체 식별자로 `UUID` 외에 어떤 형식이 사용될 수 있을까요?

**Comment by jaceshim** [comment]
@gyuwon 우선 제가 이해하고 있는 수준으로 말씀드리면
Member aggregate의 식별자는 String type의 user id가 될수도 있고 Order Aggregate의 식별자는 Long type의 order  id가 될수도 있지 않을까요?

**Comment by gyuwon** [comment]
@jaceshim 사용자 식별자는 문자열이고 주문 식별자는 숫자라고 정의하시는 이유가 무엇인가요?

**Comment by jaceshim** [comment]
@gyuwon 정의에 이유가 있는게 아니구요~ 저의 의견은 loom을 사용해서 이벤트 소싱을 구현할때 저런식의 식별자를 쓰길 원하는 경우가 있을것 같아 예를 든것입니다.

**Comment by gyuwon** [comment]
@jaceshim 저도 그것이 궁금해서 질문드린 것인데요, 레거시 시스템 마이그레이션의 경우를 제외하고 이벤트 소싱이나 여타 비동기 시스템에서 저런 식별자(128비트 데이터가 아닌) 형식을 사용하길 원하는 이유가 무엇인가 하는 것이 질문의 요지였습니다. 이것은, 위에서 말씀드리고 관련 문서를 링크했 듯 이벤트 소싱 뿐 아니라 비동기 시스템에서 식별자가 `UUID`가 아닌 경우 극복해야 할 과제가 많기 때문에 꽤 중요한 요인이라고 생각됩니다.

**Comment by jaceshim** [comment]
@gyuwon
후딱 날 잡아서 이것저것 얘기 듣고 싶습니당~ 
저도 기존 프레임웤들이 어떻게 식별자를 정의하고 지원하는지 좀 도 찾아보겠습니다! :-)

**Comment by gyuwon** [comment]
@jaceshim 그럼 이 이슈는 다시 닫고 필요한 경우 재논의 하도록 하겠습니다.

**Comment by mhyeon-lee** [comment]
아래와 같은 인터페이스와 클래스를 제공해서 사용하는건 어떨까요?
값은 UUID 를 사용하되, OrderId 와 같이 타입을 정하고 싶은 사람들은 Guid 를 구현하거나 Identifier 를 상속해도 될거 같습니다.

``` java
public interface Guid {
      UUID getValue();
}

public class Identifier implements Guid{
      private UUID value;

     private Identifier(UUID value) {
           this.value = value;
     }
     public static Identifier generate() {
          return new Identifier( UUID.randomUUID());
     }
      public UUID getValue() {
            return this.value;
      }
}
```

**Comment by jaceshim** [comment]
@all
Java에서 기본 제공되는 String 또, Integer,Long 등의 wrapper타입 외에 별도의 custom type 식별자를 많이 사용하나요? 제 경험에는 custom type의 식별자를 사용해본적이 없어서 다른 분들의 경험이 궁금해서 질문드립니다

**Comment by mhyeon-lee** [comment]
옛날 legacy 시스템에 종종 자연키가 키를 잡힌경우는 String 등이 보였고, 
mysql 의 auto-increment 나 JPA의 @GeneratedValue 를 사용한 경우에 Long 으로 식별자를 많이 잡는거 같았습니다.

저는 최근에는 UUID 를 사용하긴 하는데 필요에 따라서 위와 같이 wrapping 해서 사용하기도 합니다.

**Comment by jwChung** [comment]
@jaceshim domain-model과 persistent-model간 타입을 구분하느냐 그렇지 않느냐에 따라 달라진다고 생각해요. 

**구분하는 경우**
Person이란 클래스를 생각해보죠. email이 식별자라면 domain-model 경우 식별자는 Email라는 custom type을 만드는 게 좋습니다. 이 클래스를 통해 올바른 email 형식의 문자열을 입력받았는지 생성자에서 검사할 수 있습니다. Email 클래스 타입을 사용하는 것으로 항상 유효한 email 형식이라는 것을 보장할 수 있습니다. 하지만 DB 엔티티 persistent-model 경우 Email custom type로 표현할 수 없으니 String을 사용해야합니다. 이 경우 domain-model과 persistent-model간 변환 비용이 듭니다.

**구분하지 않는 경우**
domain-model과 persistent-model을 따로 구분하지 않는다면 email을 string으로 표현해야 합니다. 이 경우 변환 비용이 들지 않는 장점이 있지만 앞서와 같이 type에 비지니스 요구사항을 반영하지는 못합니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 위에서 말씀드렸던 내용입니다.

> `OrderId`와 같은 형식을 사용할 경우 이벤트 저장소는 이를 어떻게 처리해야 할까요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
도메인 식별자를 인프라 계층인 저장소에서 알고 있을 필요는 없을거 같다고 생각됩니다.
아래와 같이 Repository 까지는 도메인 식별자로 받고, EventStore 에서는 저장소의 PK 가 되는 UUID 값을 받으면 어떨까 합니다.


``` java
public class OrderRepository implements Repository<Order> {
    private final EventStore eventStore;

    public OrderRepository(EventStore eventStore) {
        this.eventStore = eventStore;
    }

    @Override
    public void save(Order order) {
        UUID storeId = order.getId().getValue();
        eventStore.saveEvents(storeId, order.pollAllPendingEvents());
    }

    @Override
    public Optional<Order> load(OrderId orderId) {
        UUID storeId = orderId.getValue();
        Iterable<DomainEvent> events = eventStore.getEvents(storeId);
        if (!events.iterator().hasNext()) {
            return Optional.empty();
        }
        Order order = new Order();
        events.forEach(order::apply);
        return Optional.of(order);
    }
}

public interface EventStore {
    void saveEvents(UUID id, Iterable<DomainEvent> events);

    Iterable<DomainEvent> getEvents(UUID id);
}
```

**Comment by jaceshim** [comment]
@jwChung 네~ Domain Model관점에서 보면 그렇게 풀어볼 수 있겠지만요~
사실 Entity의 식별자는 Entity의 생성시점에서 Validation을 수행해서 생성되기 때문에
굳이 식별자를 별도의 Custom type으로 분리하는것이 얼마나 현실적으로 도움이 되냐에 대한 의도로 질문을 드린것입니다. 말씀해 주신것 처럼 식별자를 별도의 custom type으로 분리하는 경우 영구저장소에 저장되는 시점에 여러가지 불편함 점들이 존재하고 실제 현업에서 이런 불편함이 존재하는데도 불구하고 
별도의 custom type의 식별자로 분리해서 구현하시는지에 대해 질문드린것입니다~

**Comment by jwChung** [comment]
@jaceshim 헛다리 짚었군요. 적으면서도 좀 이상하다 했습니다 ㅋㅋ.

**Comment by jaceshim** [comment]
@jwChung 헛다리라뇨~ 이런식의 건전하고 발전적인 온라인 커뮤니케이션이 얼마만인지 몰라서 너무 좋아요! :-)

**Comment by gyuwon** [comment]
@mhyeon-lee 그렇게 하면 처리할 수도 있겠네요. 그런데 `UUID`를 직접 사용할 수 없다는 것이 큰 단점이 아닐까요? `UUID`를 캡슐화 하고자 하는 욕구가 어느 정도 있을지 모르겠습니다.

**Comment by mhyeon-lee** [comment]
@gyuwon 
네 저도 꼭 custom-type 을 제공해야 된다는 주장은 아니지만 복잡성에 비해 필요성이나 효과에 대해서 짚고 가고자 이야기를 꺼냈습니다.

추가적으로 떠오르는 사례로는 도메인 중심으로 설계 했을때 도메인 식별자와 저장소(DB) 식별자가 일치하지 않는 경우입니다. 
예를 들어 Project 라는 도메인에 Account 들이 가입할 수 있을때 그 관계를 관리하는 도메인을 Participant 라고 명명하겠습니다. 
이 경우 Participant 의 도메인 식별자로 가까운 것은 UUID 같은 값이 아닌 projectId 와 accountId 의 조합이 도메인 식별자가 될거 같습니다.
`participant1.getId().equals(participant2.getId())` 가 되려면 ID 의 equals 는 UUID 가 아닌 projectId + accountId 조합으로 비교해야 합니다.
Participant 도메인 입장에서는 projectId + accountId 가 도메인 식별자고 UUID 는 persistence 레벨의 식별값이 될거 같습니다.

보통 이렇게까지 도메인과 저장소를 분리해서 관리하지 않기는 합니다.
저런 케이스의 경우 Participant entity 의 equals() 에서 비교하도록 했었네요

**Comment by mhyeon-lee** [comment]
UUID 로 진행하고 추후 별도의 필요성이 발생하면 다시 논의하도록 하겠습니다.
