### ISSUE TITLE
비동기호출 지원

### ISSUE THREAD

**Issue by jwChung** [loom/loom-java#15]
아래와 같은 `saveEvents` `getEvents` 메소드는 대게의 경우 비동기 호출에 해당합니다. 비동기 호출을 지원할 방법이 있습니까?

```java
public interface EventStore {
    void saveEvents(UUID id, Iterable<DomainEvent> events);

    Iterable<DomainEvent> getEvents(UUID id);
}
```

**Comment by mhyeon-lee** [comment]
네 비동기 지원도 필요할거 같습니다. 
Future 같은걸 사용할 수 있는데 우선은 너무 많은걸 고려하면 복잡할거 같아서 비동기 및 동시성 등은 고려하지 않았습니다.

**Comment by jwChung** [comment]
나중에 도입하면 수정비용도 만만치 않은 것 같아서 시작단계에서 도입하는 것이 어떨까 하는 생각에 이슈를 제기했습니다. 가볍게 고려하지 않고 시작하다 나중에 고민하는 것이 좋을런지요?

**Comment by mhyeon-lee** [comment]
jdbc 에서 아직 비동기를 지원하지 않아서 jdbc 를 사용하거나 이를 사용하는 프레임워크들이 제대로 비동기를 지원하지는 못합니다.

그래서 비동기 지원 인터페이스는 별도로 만드는게 어떨까 합니다.

**Comment by gyuwon** [comment]
저도 고민이 됩니다. Java 생태계에서 아직은 비동기 프로그래밍이 일반적이지 않아서 .NET 처럼 비동기 프로그래밍을 위한 데 팍토 표준 인터페이스가 없다보니 어떤 인터페이스를 차용하는 것이 좋은지도 결정하기 쉽지 않네요.

@mhyeon-lee 아마 @jwChung 님의 의견은 인터페이스 정의를 말씀하시는 것으로 보입니다. JDBC가 아직 비동기 입출력을 지원하지 않아도 비동기라 함은 `동기적이거나 아니거나`를 의미하기 때문에 비동기 인터페이스를 제공하며 구현을 동기적으로 처리해도 되고, 이렇게 하면 추후 비동기 구현을 적용하더라도 클라이언트에 설계의 breaking change를 요구하지 않을 테니까요.

**Comment by mhyeon-lee** [comment]
`Future<Iterable<DomainEvent>> getEvents(UUID id); `

로 해도  구현에서 동기로 하면 동기로 동작하는건 맞습니다만, 
아무래도 Future 로 한번 wrapping 이 되면 항상 동기로만 사용하는 쪽에서 불편함이 있을거 같아서 의견을 드렸습니다.
java 쪽에서는 아직 Future 와 같은 비동기 인터페이스에 대해 익숙하지 않은 개발자들이 많은거 같아서요

추후에 jdbc 도 비동기를 지원하게 될거고 비동기의 필요성도 커지고 있는 만큼 Future 로 가는것도 괜찮겠습니다.

다른분들의 의견은 어떠신가요?

**Comment by gyuwon** [comment]
이 부분에 대해서는 저는 정보가 부족해서 강한 의견은 없습니다. 다른 분들의 합의를 따르겠습니다.

**Comment by jwChung** [comment]
@gyuwon  님 말씀과 같이 수정 비용에 대한 걱정이었습니다. @mhyeon-lee 님 의견처럼 따로 인터페이스를정의한다면 수정 비용을 크게 고민하지 않아도 되겠네요. 저도 비동기 지원에 대한 자바 생태계를 몰라서 다른 분들 합의에 따르겠습니다.

**Comment by gyuwon** [comment]
그럼 이 이슈는 닫고 비동기 처리에 대해서는 추후 논의하겠습니다.
