### ISSUE TITLE
최상위 패키지 이름

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#16]
현재 loom-core 프로젝트의 최상위 패키지 이름은 `io.loom.core`입니다. `core`를 지우고 `io.loom`을 최상위 패키지 이름으로 하는 것은 어떨까요?

**Comment by jaceshim** [comment]
전 찬성입니다!
core 자체가 이미 특정 역할을 부여받은 의미로 받아들여질수 있을것 같기에
io.loom이 최상위 패키명이 되는게 좋을것 같습니다

**Comment by mhyeon-lee** [comment]
현재 repository 명이 loom-core 인데 loom-eventstore 등이 생길때 모두 io.loom 으로 시작하면 패키지명 중복이 생길거 같아서 core 를 붙였습니다.

**Comment by jaceshim** [comment]
@mhyeon-lee @gyuwon
아 그럼 이미 core는 loom에서 핵심적인 구현들이 위치하는 패키지인거네요? 이를 테면 어그리거트 인터페이스 또는 그의 추상클래스 이런것들요?
이런것들이 구현되는거라면 이건 최상위 패키지가 아니라
이미 core 구현 패키지가 되는거니 바꿀필요는 없겠네요!

**Comment by mhyeon-lee** [comment]
네 다른분들은 어떤 의견을 가질지 모르겠는데 저는 core 에서 핵심 인터페이스 및 추상 클래스들을 제공하고
loom-eventstore 등에서 core 의 인터페이스를 구현한 구현체들(rdbms, redis 등등) 이 나오는게 어떨까 생각하고 있습니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 의도는 저도 동의합니다. 그 의도를 이렇게 구현하면 어떨까 하는 것이에요.

```text
- io.loom
  - io.loom.aaa
    - io.loom.aaa.ccc
  - io.loom.bbb
```

**Comment by mhyeon-lee** [comment]
위의 예에서 aaa 가 core 가 되는거지요?

처음에 Loom 샘플을 만들었을때는 io.loom 으로 시작했는데, Loom.java 를 제거하면서 io.loom.core 가 최상위가 되버렸군요

**Comment by gyuwon** [comment]
@mhyeon-lee 아닙니다. 제가 제시한 것은 `io.loom.core` 역할을 `io.loom`이 하는 것입니다.

그런데 위 댓글을 보니 패키지 이름 충동 가능성을 말씀하셨는데요, Java의 패키지는 닫힌 범위인가요? 다시 말해 loom-core에서 `io.loom` 패키지를 사용하면 loom-eventstore에서는 `io.loom` 패키지에 형식을 추가할 수 없게 되나요?

**Comment by jaceshim** [comment]
@gyuwon 할 수는 있습니다! 다만 패키지 계층에 따라 암묵적 의존 관계가 형성되어 있기에 실제 io.loom 프로젝트 모듈에서 공통으로 사용하면 실제 loom을 사용하여 코드 구현시에 많이 불편하고 혼동될 소지가 있을것 같습니다

**Comment by mhyeon-lee** [comment]
네 @jaceshim 님 말씀대로 혼동의 여지가 있어서  충돌이라기 보다는 중복이라는 표현을 사용했습니다.

**Comment by jaceshim** [comment]
여기서 암묵적 의존관계랑 특정 패키지 하위 패키지는 그의 상위 패키지에 종속적이다! 라고 이해하시면 될것 같어요

**Comment by gyuwon** [comment]
그렇다면 `io.loom.core` 대신 `io.loom`을 사용해도 @jaceshim 님이 말씀하신 규칙을 어기는 경우는 거의 발생하지 않을 것 같은데 어떠신가요?

**Comment by mhyeon-lee** [comment]
네 서브 프로젝트에서 io.loom 을 최상위로 사용하지 않는다면 괜찮을거 같긴합니다.

loom-core: io.loom
loom-eventstore : io.loom.eventstore
loom-emitter: io.loom.emitter

**Comment by jaceshim** [comment]
@gyuwon 그렇긴 한데요~
이렇게 되면 사용하는 사람 입장에선 광장히 혼란 스러워 지거든요~ 코딩시 오토 서제스트 같은 기능을 이용하면io.loom 패키지 하위로 다 검색되서 많이 혼란 스러울 겁니다! 경험상 분리하는게 맞다고 봅니다.

**Comment by gyuwon** [comment]
그렇군요. 그러면 이 이슈는 닫겠습니다.
