### ISSUE TITLE
pollEvents() 메서드 역할과 이름

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#17]
@mhyeon-lee `AggregateRoot.pollEvents()` 메서드 이름에서 `poll`이란 어떤 의미로 사용된 것인가요?

```java
public interface AggregateRoot extends Serializable {
    Iterable<DomainEvent> pollEvents();
}
```

https://github.com/loom/loom-core/blob/06b714c3eed2abd89df422ba0583bfdbbdf85b1d/src/main/java/io/loom/core/aggregate/AggregateRoot.java#L16

**Comment by mhyeon-lee** [comment]
Aggregate 에서 raise 된 이벤트들을 꺼내서 store 에 저장할때 이 메소드를 수행합니다.
꺼낸 이벤트를 Aggregate 에 남기지 않고 제거하기 때문에 Queue 에서 poll 을 사용했습니다.

더 적절한 용어가 있으면 의견주시기 바랍니다.

**Comment by gyuwon** [comment]
poll이란 말이 그런 의미를 가지는지 몰랐네요.

https://docs.oracle.com/javase/7/docs/api/java/util/Queue.html#poll()

말씀하신 역할을 담당하는 메서드라면 `pollAllPendingEvents()`라고 하면 어떨까요?

**Comment by mhyeon-lee** [comment]
네 역할이 더 명확하네요 이것도 바꾸겠습니다.
