### ISSUE TITLE
제네릭 인수 명명 관습

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#18]
Java의 제네릭 인수 명명 관습에 대해서는 조금 찾아보니 주류가 되는 규칙이 없는 것 같습니다. [현재 `Repository<>` 인터페이스](https://github.com/loom/loom-core/blob/06b714c3eed2abd89df422ba0583bfdbbdf85b1d/src/main/java/io/loom/core/aggregate/Repository.java#L9)는 대문자를 사용하고 한 문자로 축약하지 않았습니다.

구글링 해보니 다음과 같은 글이 있는데요,

https://dzone.com/articles/naming-conventions

다른 의견들도 모아봤으면 합니다.

**Comment by jwChung** [comment]
![image](https://cloud.githubusercontent.com/assets/3784448/25758374/4d735b06-3209-11e7-9781-9fab838e2579.png)

Google Java Style (checkstyle 7.6.1)을 따른다면 위 그림에서 보듯이 generic type argument 명명 규칙이 
 `AGGREGATE` 에서 `AggregateT` 로 변경되어야 합니다. Google Java Style 를 따르는 것이 어떨까 합니다.

관련된 Google Java Style Guide는 아래 링크를 참고하세요.

https://google.github.io/styleguide/javaguide.html#s5.2.8-type-variable-names

**Comment by mhyeon-lee** [comment]
네 AggregateT 로 바꾸는게 좋겠네요

**Comment by gyuwon** [comment]
@mhyeon-lee 님 할당해 드리겠습니다. 다른 분께 토스하셔도 상관없어요. :)

**Comment by mhyeon-lee** [comment]
넵 https://github.com/loom/loom-core/pull/19  이거 merge 되면 수정하겠습니다.

**Comment by jwChung** [comment]
@mhyeon-lee #19 에서 `AggregateT`로 수정되었습니다.

**Comment by mhyeon-lee** [comment]
넵 감사합니다.
