### ISSUE TITLE
프로젝트 초기 구축

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#2]
`loom-core` 프로젝트의 초기 구조를 만듭니다.

- [x] 1. 테스트 도구
- [x] 2. 코드 커밋 절차
- [x] 3. 빌드 도구 : Gradle
- [ ] 4. 배포 프로세스

**Comment by mhyeon-lee** [comment]
아래 내용으로 의견냅니다.

* 테스트 도구: JUnin4
* 빌드 도구:  Maven vs Gradle 
* 코드 커밋 절차:  branch -> pull requests -> review -> merge to master

**Comment by gyuwon** [comment]
@mhyeon-lee 배포 프로세스는 바이러니 배포 절차를 의미했습니다. 말씀해주신 것은 코드 커밋 절차로 보이는데 해당 항목을 추가하겠습니다.

**Comment by mhyeon-lee** [comment]
테스트 도구 중 assertj 도 추가하면 좋겠습니다.
http://joel-costigliola.github.io/assertj/

**Comment by jwChung** [comment]
버전닝은 [semver](http://semver.org/) 따르는 것이 어떨까요?

**Comment by mhyeon-lee** [comment]
테스트 도구 중 mocking 도 필요하겠네요
@jaceshim 저는 주로 mockito 사용했는데 선호하시는 mocking 도구 있으신가요?
http://site.mockito.org/

**Comment by mhyeon-lee** [comment]
https://github.com/loom/loom-core/pull/3  여기에서 다른 분들은 특별한 이견이 없었던 걸로 봐서 빌드 도구는 Gradle 로 정해도 되겠군요

혹시 eclipse 사용하시는 분 있으면 말씀해주세요

**Comment by mhyeon-lee** [comment]
@jaceshim 
lombok 은 어떻게 할까요? 
의존성을 적게 가져가는게 좋긴 하지만 스프링 같은 프레임워크에서도 lombok 을 적극 사용하는거 같긴합니다.

**Comment by jaceshim** [comment]
@mhyeon-lee
그러게여 좀 고민이 됩니다~
저도 lombok을 좋아라 잘 쓰고 있지만
의존성이 약간 걸리네요
lombok에서 주로 쓰는
어노테이션이 core내 구현체들에서 많이 쓰이진 않을것 같기도 하고 core의 경우 의존성을 최소화 하는 측면에서 lombok은 안쓰는거로 하는건 어떨까 싶습니다.

**Comment by mhyeon-lee** [comment]
넵 그럼 lombok 은 제외하는걸로 하겠습니다.

**Comment by mhyeon-lee** [comment]
1. 테스트 라이브러리는 의존성 고민 없이 추가해도 될거 같습니다. 우선 아래 2개의 라이브러리를 제안합니다.
       - assertj :  http://joel-costigliola.github.io/assertj/
       - mockito : http://site.mockito.org/
       - awaitility (추후 비동기 테스트 필요시) : https://github.com/awaitility/awaitility

2. 코드 커밋 절차는 암묵적으로 아래와 같이 진행되는데 합의하는거 같습니다. 좀 더 자세한 룰은 별도 이슈에서 논의하고 정하는게 좋겠습니다.
       * new branch and coding
       * pull request and request review
       * review and approve
       * merge to master

3. Gradle 로 사용하고 있습니다. 다른 도구가 필요하다면 언제든지 의견 주시면 됩니다.

4. 바이너리 배포 절차는 방향성을 잡고 0.0.1-SNAPSHOT version 정도 진행됐을 때 다시 논의해보면 좋을거 같습니다.

**Comment by mhyeon-lee** [comment]
이 이슈는 닫겠습니다.
1번과 3번은 추가 논의가 필요한 경우 다시 Open 하변 됩니다.

2번과 4번은 별도 이슈로 의견 교환 및 룰을 정하면 좋을거 같습니다.
