### ISSUE TITLE
PR 병합 정책

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#21]
PR 병합 조건으로 핵심 인원 2명의 승인을 결정했습니다. 2명 이상의 승인후 PR 작성자가 직접 병합하시는 것이 어떨까합니다. 그리고 병합 방법은

- 병합 커밋
- 스쿼시
- 리베이스

중 어떤 것이 좋을까요?

**Comment by mhyeon-lee** [comment]
병합 커밋이 불필요한 커밋이 추가된다고 꺼려하는 분들도 있는데, 저는 작업 단위를 볼 수 있어서 나쁘지 않다고 생각하는 편입니다.

**Comment by jwChung** [comment]
병합 커밋 +1

PR 작업 단위를 파악할 수 있어서 저도 병합 커밋 좋아합니다.

**Comment by gyuwon** [comment]
저도 병합 커밋 한 표입니다. 리베이스는 트리가 너무 복잡해지지 않도록 각자 알아서 하는 것으로 하면 될 듯요.

**Comment by gyuwon** [comment]
생각해봤더니 두번째 승인자가 병합하기보단 두명의 승인 후 PR 작성자가 병합하는 것이 더 좋겠네요. 이슈 본문 수정하겠습니다.

**Comment by jwChung** [comment]
> 생각해봤더니 두번째 승인자가 병합하기보단 두명의 승인 후 PR 작성자가 병합하는 것이 더 좋겠네요.

@gyuwon 왜 이렇게 생각하셨는지요?

**Comment by mhyeon-lee** [comment]
저도 @gyuwon 님 정정 의견처럼 PR 올린 본인이 최종 merge 하는게 장점이 있을거 같습니다.

2명 이상이 approve 했더라도 최종 merge 전에 정리할 사항이 필요할 수 있고, 특히 conflict 가 발생해서 merge 를 위한 추가 작업이 필요한 경우도 결국 작성자가 해야되기 때문에 장점이 될거 같습니다.

**Comment by mhyeon-lee** [comment]
병합 커밋을 남긴다면 merge 시 메시지에 reviewdBy 를 남겨 리뷰어를 남겨주는것도 좋다고 생각합니다.

**Comment by jaceshim** [comment]
@jwChung 저도 PR올린분이 승인 통과하면 merge하는것에 찬성합니다!

**Comment by mhyeon-lee** [comment]
추가로 PR 올린사람이 2명 이외에 다른 분에게 리뷰를 더 받고 싶을 수 있는데 2번째 Approve 한 사람이 merge 하면 그 기회를 잃을 수도 있을거 같군요

**Comment by jwChung** [comment]
@jaceshim 저는 반대 의견이 아니고 @gyuwon 님 생각이 궁금했습니다. 예전에 github에 리뷰 승인 기능이 없을 때는 작성자가 PR병합하는 것이 좋지 않다고 저는 생각했었습니다.

**Comment by gyuwon** [comment]
@jwChung PR 작성자가 꼭 리뷰받고 싶은 대상이 있다거나 만장일치였으면 좋겠다거나 하는 작업도 있을 것 같아서요.

**Comment by gyuwon** [comment]
제가 몰랐는데 GitHub의 PR은 병합 불가능 상태를 만들지 못하는 것 같습니다. 두 명 이상의 승인이 있어도 누군가 중대한 이유를 발견했다면 PR의 병합을 막을 수 있어야 한다고 생각하는데요. 어떤 방식이 좋을까요? @mhyeon-lee @jwChung @jaceshim @enshahar @LeeKyoungIl

**Comment by mhyeon-lee** [comment]
라벨을 붙이고 해당 문제가 해결됐다면 붙인사람이 떼는건 어떨까 합니다

**Comment by gyuwon** [comment]
리뷰 상태를 `Request changes`로 바꾸니 병합이 불가능하지는 않지만 시각적으로 표현해주네요. 레이블도 병합 불가를 강제할 수는 없으니 `Request changes` 리뷰 상태가 있는 경우 병합하지 않도록 하는 것이 지금으로서는 최선이 아닐까 싶네요.

**Comment by jwChung** [comment]
@all
위 의견을 반영하여 master 브랜치 병합 강제사항을 두었습니다.

1. CI를 통과해야한다.
2. 한명 이상의 approved 가 있어야 한다. 우리 정책은 2명인데 이렇게 설정은 불가하네요.
3.  changes requested 요청하는 분이 없어야 한다.

자세한 내용은 아래 설정페이지를 참고하세요.
https://github.com/loom/loom-core/settings/branches/master

**Comment by gyuwon** [comment]
@jwChung 오 그런 설정이 있었군요!

그러면 PR 병합에 대해 이렇게 정리하고 이슈를 닫도록 하겠습니다.

- CI를 통과해야 한다.
- 2명 이상의 승인(approved) 리뷰가 있어야 한다.
- 변경 요청(changes requested) 리뷰가 없어야 한다.
- 특별한 문제가 없다면 PR 작성자가 병합한다.
- 병합 커밋을 사용한다.
