### ISSUE TITLE
MemoryEventStore 구현

### ISSUE THREAD

**Issue by jwChung** [loom/loom-java#23]
EventStore에 가장 기본이 되는 것이 MemoryEventStore 입니다. MemoryEventStore 구현 제안합니다.

**Comment by mhyeon-lee** [comment]
중요한건 아니지만 클래스 이름관련하여 메모리 저장소 관련 여러 클래스들의 이름이 InMemoryXXX 로 명명된 것을 많이 본거 같습니다.

**Comment by LeeKyoungIl** [comment]
MemoryEventStore 라면 

1. 외부에 있는 inMemory 기반의 Redis나 Memcached 같은 솔루션을 이용한 MemoryEventStore
2. Java의 Collection을 이용한 저장소 

둘중에 어떤것을 말씀 하시는 것인가요?

**Comment by LeeKyoungIl** [comment]
어익후 미리 의논 하셨던 이슈들 처음부터 다 읽어 봐야 겠네요.

**Comment by jwChung** [comment]
@LeeKyoungIl 저는 2번 의미로 제안드렸습니다. 제안한 in-memory event store는 운영이 아닌 테스트 목적으로 활용될 가능성이 높습니다. 상대적으로 심플한 구현이어서 먼저 제안했습니다.

**Comment by LeeKyoungIl** [comment]
@jwChung 괜찮네요 그래도 무한히 쓰는것 보단 Heap 에 보관하는 메모리 용량을(최대) 설정이 가능하도록 옵션도 있으면 좋을꺼 같습니다. (더불어 MAX용량이 차면 어떤 방식으로 지울것 인지도 LRU등등..)

**Comment by mhyeon-lee** [comment]
EventStore 에 저장되는 Event 는 용량이나 다른 이유로 지우면 안될거 같습니다.
메모리를 over 하면 Exception 을 내서 테스트를 실패시켜야 될거 같습니다.

이후에 snap-shot 정책이 들어가면 그걸 활용해서 정리를 할 수도 있겠네요

**Comment by gyuwon** [comment]
최근에 메모리 중심으로 구동되는 저장소가 등장하면서 `in memory`라는 용어가 기존과 좀 혼동되는 건 사실인 듯 합니다. 그래서인지 요즘엔 휘발성 메모리 기반 저장소 구현체에 `in process`라는 표현을 쓰기도 합니다. 그런데 이런 구현체는 fake 외의 역할을 하지 못한다고 보는데 loom-core 프로젝트가 제공하는 것이 적절한지 의문입니다.

**Comment by jaceshim** [comment]
@gyuwon 
in Memory EventStore는 loom-core에서 제공할 필요는 없다고 봅니다.
`EventStore`는 반드시 영구 저장소 여만 하는데 이런 EventStore의 특성상 in Memory는 부합되지 않는다고 생각합니다.

**Comment by mhyeon-lee** [comment]
네 production 에서는 사용하지 않지만
테스트를 위한 fake 제공 또는 loom-core 를 특별한 저장소 설정 셋팅 없이 바로 테스트로 한번 사용해보고 싶은 사용자에게 편의를 위한 구현체 정도로 여겨질 수 있을거 같습니다.

이정도 편의를 제공할지 말지 여부에 따라 구현 여부를 결정하면 될거 같네요

저는 처음 사용하는 사용자에게 접근성을 높이기 위해 샘플로 하나 있어도 나쁘지 않겠다는 의견입니다.

**Comment by mhyeon-lee** [comment]
이런 편의를 위한 제공이면 별도 라이브러리로 분리하는게 합리적일 수 있겠네요

**Comment by jwChung** [comment]
fake 주 용도로 제안드렸습니다.  가볍게 시작해보자는 의도였습니다만 이런 테스트 도움 코드는 프로덕션이랑 분리되는게 좋겠네요. 이 이슈는 닫도록 하겠습니다.

**Comment by LeeKyoungIl** [comment]
@jwChung 헉 이슈를 닫으셨네요. 
제 생각에는 좋은 생각이라고 생각 됩니다.
EventSourcing 구현체 자체가 매우 무겁습니다. 돌려 보려면 messageQueue 와 eventStore를 갖추어야 테스트를 해볼수 있으니까요. 

이럴때 가령 inMemory (는 조금 무리가 있다고 생각이 됩니다만) 보다는 h2db 라던지 file을 eventStore 또는 messageQueue로 사용이 가능하도록 해주는것도 (테스트 용도 이지만 선택권은 사용자에게 일임) 정말 좋은 편의성 이라고 생각이 됩니다. 이렇게 되면 따로 infra영역을 준비 하지 않아도 본인의 laptop에서 손쉽게 테스트가 가능하니까요.

**Comment by jwChung** [comment]
@LeeKyoungIl 재오픈은 누구나 언제든 하실 수 있습니다 :)

**Comment by LeeKyoungIl** [comment]
@jwChung 그렇군요. 하하 . 
저는 이 이슈를 계속 논의 했으면 합니다. 
개발 단계에서는 infra영역을 전부 준비 하기는 어렵습니다. (물론 docker를 본인의 laptop에 설치를 하는것도 좋지만 저는 사양이 낮은 laptop을 사용하기 때문에 가급적 지양하고 있습니다. :) ) 
따라서 손쉽게 테스트를 해볼수 있도록 inMemory는 저도 좋은 생각이라곤 생각하지 않습니다만 h2나 file형식으로 테스트 환경에서 손쉽게 돌려볼수 있도록 지원해 주는것도 좋다고 생각이 됩니다.

**Comment by mhyeon-lee** [comment]
테스트 및 접근성을 높이기 위한 도구로서의 가치가 있고, production 레벨에서는 필요하지 않다는데에 모두 동의하는거 같습니다.

논의 쟁점은 loom-core 에 같이 포함시킬것인가, 별도의 라이브러리도 제공할 것인가 또는 굳이 만들 필요가 없다로 좁힐 수 있겠네요

**Comment by jaceshim** [comment]
@LeeKyoungIl 
그런 의도라면 test코드에 fixtures 로 제공해도 되지 않을까 싶어요~

**Comment by mhyeon-lee** [comment]
@jaceshim 보통 test 코드는 패킹에 포함시키지 않기 때문에 loom-core 를 사용하는 개발자가 가져올 수는 없을거 같아요

**Comment by jaceshim** [comment]
@mhyeon-lee 
앗! 그러네요... 
전 core에 in Memory EventStore를 포함시키는건 자칫 EventStore이 특성이 무시된체 사용자들에게 인지 될 수 있을것 같아서 필요하다면 별도의 라이브러리로 포함시키는게 좋을것 같습니다.

**Comment by mhyeon-lee** [comment]
@jaceshim 
네 저도 별도의 라이브러리 한표입니다.

**Comment by YoungjaeKim** [comment]
뻔한 이야기입니다만, 최근 리비전을 거친 EntityFramework Core의 경우, `.InMemory` 하부 네임스페이스에 별도 라이브러리로 구성하고 있습니다.

- 관련 위계: https://docs.microsoft.com/en-us/ef/core/providers/in-memory/
- 구현체: https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs

`(for Testing)`이라고 명시하고 있는게 친절해보이네요.

**Comment by jwChung** [comment]
@YoungjaeKim 

for testing ㅋㅋ 

역시 테스트 용은 별도 패키지로 배포하는군요.
Microsoft.EntityFrameworkCore.InMemory

**Comment by YoungjaeKim** [comment]
아이고 제 코멘트에 관련 위계 링크 복붙을 잘못했네요. 
아래 링크를 데탑에서 열어보면 목차에 (for Testing)이라고 써있습니다. 

https://docs.microsoft.com/en-us/ef/core/providers/in-memory/

**Comment by jwChung** [comment]
![image](https://cloud.githubusercontent.com/assets/3784448/25780299/95341ef0-3360-11e7-870b-aee7c8acaab9.png)

@YoungjaeKim readme 내용에도 있더군요.

**Comment by LeeKyoungIl** [comment]
그러면 이것은 나중에 별도의 라이브러리로 제공하는것으로 하고 닫습니다.
