### ISSUE TITLE
이슈 채택 정책

### ISSUE THREAD

**Issue by jwChung** [loom/loom-java#24]
#23 이슈를 제가 제안드렸는데, 이슈 채택 정책도 마련해야겠습니다.

제가 생각해 본 시나리오는 아래와 같습니다.

1. 누군가 이슈 제안
1. core 멤버 두명 이상 👍  따봉 하고,
1. 멤버들의 이견이 없을 시
1. 채택의 의미로 enhancement 라벨 부여

**Comment by mhyeon-lee** [comment]
찬성합니다.

**Comment by jaceshim** [comment]
찬성합니다

**Comment by jwChung** [comment]
@all

**하나의 이견도 없을 시** 과정 추가했습니다. 이 정책을 못보신 분들은 확인 부탁드리며 채택한 것으로 결정하겠습니다.
