### ISSUE TITLE
AbstractAggregateRoot의 책임 정의

### ISSUE THREAD

**Issue by jaceshim** [loom/loom-java#27]
현재 loom-core 프로젝트에는
`AggreagateRoot` interface가 존재하고 이를 구현하는 구현체에서 행해지는
몇몇 행위는 추상화 레벨에서 지원할 필요성이 있습니다.

그래서 `AggregateRoot` 를 구현한 `AbstractAggregateRoot` 추상 클래스가 필요할거라 봅니다.
하여 `AbstractAggregateRoot` 의 책임에 대해 정의해 봅니다.

- 발생된 이벤트에 대한 Version을 통합관리 한다.
- `DomainEvent`객체의 정보를 Aggregate객체에 반영한다.
- 발생된 이벤트를 `EventStore` 저장하기 위해 목록으로 관리한다.
- `EventStore`에 저장완료된 이벤트 목록을 clear한다.

의견들 부탁드립니다.

**Comment by mhyeon-lee** [comment]
@jaceshim 
제가 코드를 먼저 작성하고 설계를 고민하는 성향이라, AbstractAggregateRoot 를 간단하게 작성해봤습니다.
아직 PR 올리진 않았는데, 혹시 작업하고 계신게 있으시면 먼저 올리셔도 될거 같습니다.

---

우선 먼저 만들어서 올렸습니다;;

**Comment by mhyeon-lee** [comment]
* `AbstractAggregateRoot` 를 구현한 entity 에서 event 를 발생시켜 pending 시킬 수 있는 raise 메소드를 제공한다.
* `AggregateRoot` 엔티티에서 이벤트를 적용(apply) 할 수 있는 이벤트 타입에 매칭되는 핸들러를 찾아 실행시켜 줄 수 있다.
* apply 로 넘어온 event 에 대응하는 적절한 핸들러를 찾을 수 없을 때 `RuntimeException` 을 발생시키고 `AggregateRoot` 의 상태는 apply 실행전과 동일해야 한다.
* `equals / hashCode` 를 구현하며 클래스타입, id, version 이 일치하면 동일한 entity 로 식별하도록 한다.
* 발생한 Event 의 aggregateId 는 entity 의 id 와 동일해야 한다.
* 발생한 Event 의 version 은 entity 의 version 보다 커야 한다.

**Comment by mhyeon-lee** [comment]
Aggregate delete 상태에 관한 논의입니다.
https://github.com/loom/loom-core/issues/30

**Comment by mhyeon-lee** [comment]
Aggregate 가 invalid 상태가 됏을때에 관한 논의입니다.
https://github.com/loom/loom-core/issues/31
