### ISSUE TITLE
Aggregate delete 상태 관련 논의

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#30]
https://github.com/loom/loom-core/pull/28/files#diff-044cb051ab84b61669ad15fd843ba4edR24

여기에서 delete 상태와 관련된 논의를 시작했습니다.
@gyuwon 님은 Delete 이벤트도 하나의 이벤트이기 때문에 Aggregate 에서 상태를 가질 필요가 없다는 의견이었습니다.
Delete 이벤트가 발생해서 store 에 들어간 후 Repository 에서 해당 Aggregate 가 load 됐을때, Repository 는 이 Aggregate가 delete 된건지 알아야 될 수도 있고, 몰라도 될 수도 있습니다.
따라서 논의할 사항은 아래 정도로 우선 생각할 수 있겠습니다.

Repository 가 Aggregate 를 load 했을때 :

1. Aggregate 가 delete 상태인지 알 수 있도록 Aggregate 에서 delete 상태값을 가지고 Repository 는 delete 된 Aggregate 를 반환하지 않는다.

2. Aggregate 가 마지막에 delete 이벤트를 받았는지 알 수 있도록 DeleteEvent 인터페이스를 제공하고, DeleteEvent 인터페이스를 구현한 이벤트가 있으면 Aggregate 를 반환하지 않는다.

3. Delete 이벤트가 발생했을 때, ReadModel 에서 현재 상태를 처리하면된다. Aggregate 와 Repository 모두 Aggregate 의 delete 상태는 알 필요가 없다. 그러므로 Repository 는 그대로 Aggregate 를 반환한다.

4. 그외의 의견

**Comment by gyuwon** [comment]
제 의견에 조금 덧붙이면, 이벤트 소싱에서 개체 생성이나 변경과 마찬가지로 개체 삭제는 도메인 이벤트의 한 가지 입니다. 심지어 어떤 개체들은 생성 이벤트는 가지지만 삭제 이벤트는 가지지 않습니다. 그리고 읽기모델을 비롯해 연동되는 서비스에 개체 삭제는 중요한 이벤트이기 때문에 다른 도메인 이벤트들과 동일하게 취급되어서 메시지로 전달될 필요가 있습니다.

만약 `LogicallyDeletable`과 같은 인터페이스를 제공하더라도 핵심 코드로 취급하기 보다는 편의성을 위한 유틸리티로 보는 것이 좋다는 것이 제 생각합니다.

```java
public interface LogicallyDeletable {
    boolean isDeleted();
}
```

**Comment by mhyeon-lee** [comment]
@gyuwon 
이 부분에 대해서도 고민하던 부분이었는데, 제시하신 의견이 이벤트소싱의 관점에 합리적인 방법인거 같습니다.
core 인터페이스에서는 deleted 라는 상태를 신경 쓸 필요가 없고, 
제시한 방법대로 delete 를 필요로 한 엔티티에서 추가 인터페이스를 사용하는게 좋겠네요

**Comment by mhyeon-lee** [comment]
이 이슈도 LogicallyDeletable 과 같은 인터페이스를 별도로 정의하는 방향으로 결정합니다.
