### ISSUE TITLE
Aggregate Invalid 상태에 대한 처리 논의

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#31]
Aggregate 에서 event 를 처리하다 보면 예상치 못한 예외를 만날 수도 있습니다.
예외를 만날 시나리오와 조치 방법에 대해 논의해 보고자 합니다.

1. 예외가 발생할 경우
    - Event Handler 를 찾을 수 없을 때
    - Event 의 validation 체크가 실패했을 때
    - 구현한  handler 에서 Exception 이 발생했을 때
    - 그외

2. 예외 조치 방법
    - Event apply 시 현재 Aggregate 상태의 스냅샷을 뜬 후, Exception 이 catch 되면 복구
    - valid 상태 값을 두고, Exception 발생시 invalid 상태로 바꿔서 관리
    - 그외

**Comment by gyuwon** [comment]
이벤트는 명령과는 달리 돌이킬 수 없는 과거의 사실이기 때문에 검증(validation) 대상이 아닙니다.

**Comment by gyuwon** [comment]
도메인 모델의 프로세스에서 의도치 않은 예외가 발생하면 도메인 계층에서는 fail-over 하면 안되고, 따라서 집합체가 고민할 이슈가 아니라는 의견입니다. 그리고 위 댓글 내용처럼 이벤트는 검증 대상이 아니기 때문에 이벤트 처리기에서 의도한 예외가 발생하면 안되고요.

**Comment by mhyeon-lee** [comment]
> 도메인 모델의 프로세스에서 의도치 않은 예외가 발생하면 도메인 계층에서는 fail-over 하면 안되고, 따라서 집합체가 고민할 이슈가 아니라는 의견입니다.

의도치 않은 예외가 발생했을 때 그 도메인 모델을 사용하는 사용자가 그 예외를 catch 했다면, 

정상적이지 않은 상태의 도메인 객체를 어떻게 다룰 것인지는(버릴건지 다시 조회할건지) catch 한 사용자가 알아서 판단하는 이슈라는 말씀이신거지요?

**Comment by gyuwon** [comment]
@mhyeon-lee 말씀하신 것과 비슷한지만 살짝 다른데요,

집합체의 도메인 이벤트 처리기가 실행되는 경로는 두 가지입니다. 집합체 복원과 명령 실행. 여기서 명령 실행은 개체 생성자 호출을 포함합니다.

```java
public class Issue extends AbstractAggregateRoot {
    public Issue(UUID issueId, UUID authorId, String title, String content) {
        super(issueId);

        // Validate command parameters here.

        raise(new IssueCreated(issueId, authorId, title, content));
    }

    public Issue(UUID issueId, Iterable<DomainEvent> pastEvents) {
        super(issueId, pastEvents);
    }

    public void changeTitle(String title) {
        // Validate command parameters here.

        raise(new IssueTitleChanged(getId(), title));
    }
}
```

만약 명령 실행 중 예외가 발생한다면 예상된 경우와 예상되지 않은 경우로 나뉩니다. 예상된 경우는 집합체가 실행하기에 명령이 올바르지 않기 때문일 것이고 예상되지 않은 경우는 버그입니다. 올바른 명령은 이벤트를 만들고 이벤트 핸들러는 이론적으로 실패할 수 없기 때문이죠.

집합체 복원 중 집합체 클래스에서 예외가 발생한다면 이것은 항상 버그입니다.

두 경우 모두 도메인 모델에서 예외를 `catch`할 대상이 아닙니다. 버그라면 응당 그럴 것이고, 명령 검증 실패라면 서비스 계층이 `catch`해서 오류를 어딘가에 기록한 후 서비스 인터페이스에 맞게(웹 API라면 4xx 코드) 결과를 반환할 것입니다.

이 때 서비스 계층은 집합체 참조를 가지지 않습니다. 도메인 계층이 제공하는 메시지 처리기에 명령을 전달했을 뿐이겠죠.

따라서 행여 이벤트 핸들러가 버그로 인해 일부만 수행되었다 하더라도 오염된 상태의 집합체 개체가 `catch` 블록에서 접근될 수는 없습니다.

**Comment by mhyeon-lee** [comment]
네 자세히 설명해주셔서 어떤 말씀인지 이해가 됐습니다.
명령 실행과  그후 raise 시킨 Event 는 이미 떠나 버린 이벤트로 분리를 시켜야 되는데 하나의 프로세스로 묶어서 생각하면서 invalid 상태에 대한 고민을 했었던거 같습니다

**Comment by mhyeon-lee** [comment]
`이벤트 핸들러에서 발생하는 예상치 못한 예외는 버그이며, 집합체가 fail-over 나 관심을 가질 대상이 아님` 으로 간단하게 정리하고 이 이슈는 닫겠습니다.

이 이슈와 관련해서 추가적인 의견이나 질문이 있으신 분은 언제든지 open 하셔도 됩니다.
