### ISSUE TITLE
내부 변수/메소드 접근시 this / super 컨벤션

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#32]
@jwChung 님께서 `this.getId()` 와 같이 this 사용 컨벤션에 대해 문의하셔서 이슈로 남깁니다.
클래스 내부에서 변수/메소드에 접근할 때 저는 가급적 `this / super` 를 붙이는 편인데, 때로는 거추장스러워 보이기도 합니다.
특별히 이와 관련된 컨벤션에 대해 알고 있는게 없어서 논의 해보고 확정하고자 합니다.
@jaceshim @LeeKyoungIl 님도 혹시 알고 계신 컨벤션이 있으면 이야기 해주셔도 좋을거 같습니다.

**Comment by jaceshim** [comment]
@mhyeon-lee
저도 가급적 this 키워드를 사용할 주의 입니당!
찬성합니다

**Comment by LeeKyoungIl** [comment]
@mhyeon-lee 
저도 this 키워드 사용하고 있습니다.
springframework 에서도 커비터 대상으로 this를 사용하는것을 권장하고 있는걸로 알고 있습니다.

**Comment by jwChung** [comment]
현재 대다수 코딩 컨벤션은 checkstyle(google java style)로 강제되고 있어, `this` 키워드 정도는 자율에 맡기는 것도 나쁘지 않다고 생각합니다. 컨벤션을 정한다면 어느 것이 되었던 툴로 강제될 수 있었으면 좋겠다는 의견입니다.

> this 키워드 붙여주세요

이런 리뷰 달기 싫은데 말이죠. 저는 `가급적 this를 사용한다, 강제사항은 아니다` 에 한 표 행사합니다.

**Comment by mhyeon-lee** [comment]
네 저도 this 를 가급적 사용하고, 굳이 리뷰로 지적하진 않아도 될거 같습니다.
그냥 지나가다가 보이면 달아줘도 될거 같고요

**Comment by mhyeon-lee** [comment]
네 모두 같은 의견으로 보이고 이슈는 닫습니다.
