### ISSUE TITLE
도메인 이벤트 편의성 고려

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#37]
@mhyeon-lee 님께서 PR #35 에서 `AbstractDomainEvent` 클래스를 작성해주셨는데요, 기능적으로는 모두 괜찮다고 생각합니다. 다만 도메인 이벤트 구현과 관련해서 제가 [Khala.EventSourcing](https://github.com/Reacture/Khala.EventSourcing)을 개발하고, 결과물을 현업에 사용하고, 그러면서 느꼈던 불편함을 개선하기 위해 다시 프로젝트에 적용했던 내용에 대해 한 번 논의해봤으면 합니다. 내용이 길고 C#과 관련된 부분도 많지만 Java 구현에서도 관련성이 있으니 꼭 한 번씩 봐주세요.

### 불변성

도메인 이벤트는 지나간 과거의 사실이기 때문에 이론적으로 이벤트 처리기는 실패하지 않으며 이벤트는 변하지 않습니다. 그런 이유로 Greg Young은 이벤트 소싱이 함수형(functional)이라고 했습니다. 이것을 실제 프로그래밍 언어에서 구현할 때 이벤트 개체에서 변경 가능성을 제거하는 것이 첫번째 고려사항입니다. 불변개체로 만드는 것이죠. 그렇다면 도메인 이벤트 기반 클래스와 사용자 이름 변경 이벤트 코드는 다음과 같을 것입니다.

```csharp
public abstract class DomainEvent
{
    protected DomainEvent(Guid aggregateId, int version, DateTimeOffset raisedAt)
    {
        // Guard clauses here.

        AggregateId = aggregateId;
        Version = version;
        RaisedAt = raisedAt;
    }

    public Guid AggregateId { get; }
    public int Version { get; }
    public DateTimeOffset RaisedAt { get; }
}

public class UsernameChanged : DomainEvent
{
    public UsernameChanged(Guid userId, int version, DateTimeOffset raisedAt, string username)
        : base(userId, version, raisedAt)
    {
        // Guard clauses here.

        Username = username;
    }

    public string Username { get; }
}
```

### 불편함

불변성을 가지는 도메인 이벤트 개체는 기능적으로는 문제 없지만 실제로 사용하면서 불편함을 느꼈습니다. 이벤트 소싱을 사용하면 도메인에서 발생하는 거의 모든 행위들에 대해 도메인 이벤트를 작성하게 됩니다. 이것은 프로그래머가 도메인에 대해 더 학습하도록 강요하는 긍정적인 효과도 있지만 많은 코드를 작성해야 하는 번거로움도 줍니다. 사용자 이름 변경에 대한 코드는 다음과 같습니다.

```csharp
public class User : AggregateRoot
{
    public void ChangeUsername(string username)
    {
        // Guard clauses here.

        Raise(new UsernameChanged(this.Id, this.Version + 1, DateTimeOffset.Now, username));
    }
}
```

이 중 `this.Id, this.Version + 1, DateTimeOffset.Now`는 장황하고 반복적이고 지루합니다. 실제 현장에서 느껴지는 괴로움은 꽤 큰 편입니다.

그래서 Khala.EventSourcing은 `IDomainEvent` 인터페이스를 만들었습니다.

```csharp
public interface IVersionedEntity
{
    Guid Id { get; }
    int Version { get; }
}

public interface IDomainEvent
{
    Guid AggregateId { get; }
    int Version { get; }
    DateTimeOffset RaisedAt { get; }

    void Raise(IVersionedEntity source);
}
```

도메인 이벤트의 `AggregateId`, `Version`, `RaisedAt` 속성을 사용자(프로그래머)가 지정하는 것이 아니라 `IVersionedEntity`를 구현하는 집합체를 근원으로 이벤트를 발생시키면 자동으로 설정되는 것이죠. `AggregateRoot.Raise(IDomainEvent domainEvent)` 메서드는 `domainEvent.Raise(this)` 코드를 실행합니다. 그러면 `User.ChangeUsername()` 메서드는 다음과 같이 간략해집니다.

```csharp
public class User : AggregateRoot
{
    public void ChangeUsername(string username)
    {
        // Guard clauses here.

        Raise(new UsernameChanged(username));
    }
}
```

반복적인 코드는 사라지고 보다 도메인 집중적인 코드가 되었습니다.

### 새로운 문제점

코드의 가독성과 생산성은 증대되었지만 도메인 이벤트는 불변성을 잃어버렸습니다. 도메인 이벤트가 생성된 후 `Raise()` 메서드가 호출되고 이 과정에서 `AggregateId`, `Version`, `RaisedAt` 속성이 변경되기 때문입니다.

직렬화에도 문제가 발생했습니다. .NET의 de facto 표준 JSON 직렬화 도구인 Json.NET은 역직렬화할 때 공용 속성을 통한 방법과 생성자를 통한 방법 중 하나만 택합니다. 두 방식을 혼합하는 방법은 제공하지 않습니다. 물론 플러그인을 열어두고 있지만 플러그인 작성도 두 방식을 혼합하는 기능은 고려할 것이 매우 많고 어렵다는 것을 알게되었습니다. 헤더 속성의 불변성이 깨졌지만 `Username`과 같은 도메인 속성의 불변성이라도 유지하려면 도메인 이벤트는 이렇게 작성되어야 합니다.

```csharp
public class UsernameChanged : DomainEvent
{
    public UsernameChanged(string username)
    {
        // Guard clauses here.

        Username = username;
    }

    [JsonConstructor]
    private UsernameChanged(Guid userId, int version, DateTimeOffset raisedAt, string username)
        : base(userId, version, raisedAt)
    {
        // No guard clause in deserialization constructor.

        Username = username;
    }

    public string Username { get; }
}
```

오, 젠장! 오히려 코드가 더 장황해졌습니다. 불변성을 일부 잃어버렸고 번거로움을 제거하려는 원래의 목적도 달성하지 못했습니다.

### 불변성 포기

Khala.EventSourcing에서 제가 내린 결론은 물리적 불변성 포기입니다. 단, 프레임워크는 `IDomainEvent` 인터페이스의 읽기 전용 속성으로 동작하며 사용자가 작성한 도메인 속성에 대해서는 알지 못하기 때문에 프레임워크 수준에서 도메인 이벤트를 오염시킬 가능성은 거의 없습니다. 책임은 프로그래머에게 있습니다. 편의성을 주는 대신 자신의 도메인 이벤트를 보호할 책임까지 함께 준 것이죠.

물리적 불변성을 제거한 도메인 이벤트 작성과 사용 코드는 다음과 같습니다.

```csharp
public class UsernameChanged : DomainEvent
{
    public string Username { get; set; }
}

public class User : AggregateRoot
{
    public void ChangeUsername(string username)
    {
        // Guard clauses here.

        Raise(new UsernameChanged { Username = username });
    }
}
```

코드는 짧으면서도 도메인에 보다 집중되어 읽기 쉽습니다. 반복작업은 프레임워크가 담당합니다. 위와 같은 코드로 작성하면 생성된 `UsernameChanged` 이벤트 개체의 참조는 프레임워크가 가지게되고 사용자 코드는 직접 접근할 수 없게됩니다. 리플렉션 따위의 나쁜 짓을 저지르지 않는 한 한 번 만들어진 도메인 이벤트를 변경할 수 있는 수단은 없습니다.

### 그럼 Java에서는...

지금까지의 사례는 C#과 .NET에서 발생한 일입니다. 하지만 제가 지금껏 고민해 본 바로 Java 구현 역시 비슷한 문제가 발생할 가능성이 높습니다. 안타깝게도 아직 제가 Java 생태계의 직렬화 도구들에 대해 잘 알지 못해 합리적인 답을 찾을 수는 없습니다. 제가 이슈 #10 을 작성한 중요한 이유 중 하나도 이 문제입니다. 모두의 의견을 듣고 싶습니다.

**Comment by jaceshim** [comment]
다른건 좀 더 자세히 읽어 보겠습니다.
저도 코멘트 하려던 부분중에 하나가 version처리 부분입니다. 어그리거트의 책임 부분에서 거론한 적이 있지만 이벤트가 발생하여 이벤트객체를 생성할따 version증가 처리함은 반복코드 발생과 프러그래머의 실수를 유발시킬수 있는 부분이기에 framework에서 처리하는것이 좋다고 봅니다.

**Comment by mhyeon-lee** [comment]
네 비슷한 문제로 저도 고민을 했었습니다.
java 에서도 jackson 으로 deserialize 시 package-default 범위 이상의 setter 또는 전체 필드를 가진 생성자를 필요로 합니다. (다른 serializer 는 잘 모르겠습니다.) 저는 조금 불편함을 감수하고 생성자 + Builder 로 불변성을 유지하는 방향으로 했었습니다.
다행히 lombok 의 도움을 받아 조금은 쉽게 갈 수 있었습니다.

``` java
@Builder
public class IssueCreated {
    private final UUID aggregateId;
    private final long version;
    private final ZonedDateTime occurrenceTime;
    private final String title;
}

IssueCreated event = IssueCreated.builder()
          .aggregateId(this.id);
          .version(this.version + 1);
          .occurrenceTime(ZonedDateTime.now())
          .title(title)
          .builder();
```

이벤트 클래스는 간결해졌지만,   이벤트를 생성할때 id, version + 1, occurrenceTime 을 반복적으로 넘겨줘야 하는 단점은 존재합니다.

그래서 아래와 같은 방법은 어떨까 의견을 묻습니다.

``` java
public interface VersionedAggregate {
      UUID getId();
      long getVersion();
}

public abstract class AbstractDomainEvent {
     private final UUID id;
     private final long version;
     private final ZonedDateTime occurrenceTime;
    
     protected AbstractDomainEvent(VersionedAggregate versionedAggregate) {
            this(
                 versionedAggregate.getId(),
                 versionedAggregate.getVersion() + 1,
                 ZonedDateTime.now());            
     }
     
     protected AbstractDomainEvent(UUID id, long version, ZonedDateTime occurrenceTime) {
           this.id = id;
           this.version = version;
           this.occurrenceTime = occurrenceTime;
    }
}

//  이벤트 구현
@AllArgsConstructor
public class IssueCreated extends AbstractDomainEvent {
    private final String title;
    
    public IssueCreated(VersionedAggregate versionedAggregate, String title) {
            super(versionedAggregate);
            this.title = title;
    }
}
```

lombok 의 @AllArgsConstructor 에서 컴파일시 자동으로 아래와 같은 생성자를 만들어줘서 Deserialize 할 수 있습니다.
``` java
public IssueCreated(UUID id, long version, ZonedDateTime occurrenceTime, String title) {
    super(id, version, occurrenceTime);
    this.title = title;
}
```

**Comment by mhyeon-lee** [comment]
그런데 lombok 의 @AllArgsConstructor 가 상위 AbstractDomainEvent 의 필드까지 포함해서 생성자를 만들어 줘야 하는데 Intellij lombok 플러그인에서 부모의 필드를  인식 못해서 원하는 생성자를 못만들어주는 문제가 있습니다.
IDE 에서 에러이지 빌드하면 원하는 결과로 동작한다고 합니다.
https://github.com/rzwitserloot/lombok/issues/898

정말로 빌드가 잘되는지 그리고 전체 필드 생성자로 deserialize 가 잘 되는지는 아직 테스트 하지 못해서 불확실한 부분입니다. (테스트 해보고 결과를 다시 말씀드릴께요)

AbstractDomainEvent 와 IVersionedEntity 와 같은 인터페이스를 이용하여 불변성을 유지하는 방법으로 시작한 후 
위의 개발자의 구현에서의 문제는 좀 더 확인해보고 setter 여부를 결정해보는 것도 좋을거 같습니다.

**Comment by jwChung** [comment]
- 저도 id, version, 시간 설정은 프레임워크에서 제공하는 것이 좋다는 입장입니다.
관련하여 한 가지 의견이 있는데, <s>DomainEvent 를 인터페이스는 제공은 하지 않고 추상클래스만 제공하는 것은 어떨까요.</s> `void Raise(IVersionedEntity source);` 대신 AbstractAggregateRoot 내에서 AbstractDomainEvent 디폴트접근한정자 setter를 통해 id, version, 시간 설정 하고, public getter로 정보만 노출할 수 있습니다. 물론 이때 디폴트접근한정자 setter가 역직렬화 될 수 있어야 합니다. 
<s>DomainEvent 인터페이스 제공을 포기하면, 코드는 좀 더 직관적이게 됩니다.</s>

- 생성자 파라메타 /속성을 섞어서 사용함에 따르는 역직렬화 문제는 저도 java에서 경험이 없어서 모르겠네요.

**Comment by mhyeon-lee** [comment]
java 에서 단일 상속만 지원하기 때문에 추상 클래스 상속을 강제하는건 다른 클래스를 상속할 기회를 뺏어버릴거 같습니다. 그리고 AbstractDomainEvent 에서 디폴트접근한정자 setter 는 AbstractAggregateRoot 에서 밖에 접근할 수 없기 때문에 자동적으로 Aggregate entity 도 AbstractAggregateRoot 를 상속해야만 합니다. 그렇게 되면 AggregateRoot 인터페이스도 마찬가지로 필요가 없어질거 같습니다.

-- 

@jwChung 님의 아이디어를 살리면 AbstractDomainEvent 에서 디폴트접근한정자 setter 를 제공하고, AbstractAggregateRoot 에 event 가 `raise()` 됐을 때, 해당 event 가 AbstractDomainEvent 를 상속했는지 검사해서 상속했다면, aggregateId, version + 1, occurrenceTime 을 setting 해주는 방법을 사용할 수 있겠습니다.

AbstractDomainEvent 를 상속하지 않고 DomainEvent 인터페이스만 implements 했을 경우는 알아서 aggregateId, version + 1, occurrenceTime 을 셋팅을 해놓고 왔어야 하는거죠 해상 값들에 대한 체크만 해주면 될거 같습니다.

--

~~위의 방법에서는 반대 제약으로 AbstractDomainEvent 를 상속했으면, Aggregate 도 AbstractAggregateRoot 를 상속해야만 기능을 동작시킬 수 있다는 제한이 있습니다.~~

AbstractDomainEvent 도 생성자로 aggregateId, version, occurrenceTIme 을 셋팅할 수 있게 제공해주면 되니까 AbstractAggregateRoot 에 종속되지는 않겠네요

**Comment by jwChung** [comment]
@mhyeon-lee 

https://github.com/loom/loom-core/blob/87c46d1c26a62a190251e50352528f1cb3fe3ac0/src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java#L40

여기서 DomainEvent 대신 디폴트접근한정자 setter를 가진 AbstractDomainEvent를 raise 메소드에 넘겨주자는 생각이었습니다. 생각해보니 현 상태에서는 인터페이스 제공이 문제가 되지 않겠군요.

AbstractAggregate가 AbstractDomainEvent 둘은 어느 한쪽만 사용되는 것이 아니라 같이 사용되면  아래 문제를 해결할 수 있지 않나요?

>  event 가 AbstractDomainEvent 를 상속했는지 검사해서 상속했다면, aggregateId, version + 1, occurrenceTime 을 setting 해주는 방법을 사용할 수 있겠습니다.

**Comment by gyuwon** [comment]
지금까지 논의되는 내용을 보면 문제의식에 대해서는 어느 정도 공감하시는 것 같습니다.

도메인 이벤트가 2개의 생성자를 가져야 하고 그 중 하나는 Lombok에 의존하는 것을 @mhyeon-lee 님과 @jwChung 님이 의견을 함께 하시는 것 같습니다. 문제는 Lombok 의존적이라는 것과 그럼에도 불구하고 아직 깨끗한 답이 나오진 않았다는 것 같습니다.

이상 중간 정리였습니다. :)

**Comment by mhyeon-lee** [comment]
더 좋은 방법을 찾아볼 수 있겠지만 현재 나온 의견 중에서는 2가지 방법 중 하나를 고려해볼 수 있을것 같습니다.

1. 불변 객체 지원 AbstractDomainEvent 클래스와, 
header 정보(aggregateId, version, occurrenceTime) 후처리 setting 을 지원하는 Abstract 클래스 분리

   - 장점: 개발자에게 선택권을 줄 수 있다.
   - 단점: 추상 클래스 2벌을 관리해야 한다. 후처리 setting 지원 클래스를 상속한 이벤트가 정상 동작하려면 AbstractAggregateRoot 를 상속한 aggregate 에서 `raise()` 가 호출 되어야 후처리가 정상 동작한다.
<br/><br/>

2. AbstractDomainEvent 불변성을 포기한다. 단, setter 의 공개 범위는 package-public 으로 지정하여, AbstractAggregateRoot 에서만 접근할 수 있도록 한다.

   - 장점: 이벤트 생성시 개발자의 실수를 줄이고, 간결한 코드를 만들도록 유도할 수 있다.
   - 단점: 완전 불변 객체가 될 수 없다. 하지만 개발자가 직접 변경할 수 없으므로 reflection 을 사용하는게 아니면, 불변하도록 유지할 수는 있다.

**Comment by mhyeon-lee** [comment]
@gyuwon 제기하신 이슈에서 원칙(불변성)과 편의성 사이에서 합의점을 찾는 과정을 공유해주셨고 더 좋은 방법을 고민해보자는 내용인거 같습니다. #40 에서는 다른 대안을 제시하면서 역시 발생한 한계점을 공유해주셨습니다.

#40 에서 아래와 같은 언급을 하셨는데요
> 그런데 도메인 이벤트의 물리적 불변성 확보가 이 모든 것들의 희생을 치를만큼 가치를 가지는가 하는 의문이 생깁니다. 이론적으로 이벤트 소싱의 이벤트 저장소는 변경과 삭제가 없고 추가만 있습니다. 그런데 물리적으로도 그런가요? SQL 데이터베이스에 구축된 이벤트 저장소는 UPDATE 명령과 DELETE 명령을 차단하나요? 우리는 이벤트 소싱을 위해 변경과 삭제가 없는 데이터베이스부터 만들어야 하나요?

저도 불변성을 가능하면 지켜야 겠지만 trade-off 로 더 좋은 가치를 얻을 수 있다면 반드시 지켜야 하는 부분은 아니라고 생각합니다. 위에 제시하신 방법대로 여러 안전장치를 두면 Reflection 같은 방법을 사용하지 않고는 값을 바꾸지 못하게 할 수도 있고요

제시하신 시나리오를 저희 코드로 표현하면 아래와 같을거 같습니다.
맞나요?

``` java
public interface VersionedAggregate {
     UUID getId();
     long getVersion();
}
public abstract class AbstractAggregateRoot implements AggregateRoot, VersionedAggregate {
      // id, version
      
     protected void raise(DomainEvent domainEvent) {
             // check domainEvent is not null

              domainEvent.raisedBy(this);

              // apply to handler
              // pending
      }
}

public abstract class AbstractDomainEvent implements DomainEvent {
     private UUID aggregateId;
     private long version;
     private ZonedDateTime occurrenceTime;

   // AggregateRoot 에서의 raise() 와 구분하기 위해 임의로 raisedBy() 라고 우선 명명했습니다.
    public void raisedBy(VersionedAggregate versionedAggregate) {
          this.aggregateId = versionedAggregate.getId();
          this.version = versionedAggregate.getVersion() + 1;
          this.occurrenceTime = ZonedDateTime.now();
    }

    public void setAggregateId(UUID aggregateId) {
          this.aggregateId = aggregateId;
    }
    public void setVersion(long version) {
         this.version = version;
    }
    public void setOccurrenceTime(ZonedDateTime occurrenceTime) {
         this.occurrenceTime = occurrenceTime;
    }
}

//  개발자 구현
public class Issue extends AbstractAggregateRoot {
     // id, title, ....

      public void changeTitle(String title) {
             super.raise(new TitleChanged(title));
      }
}

public class TitleChanged extends AbstractDomainEvent {
    private  String title;
    
    public TitleChanged(String title) {
           this.title = title;
    }

    // getter;
}
```

불변성을 못지키는 부분보다 다른 관점에서 조금 우려되는 부분이 있습니다.

다음과 같은 이벤트 생성 및 셋팅 프로세스를 이해해야 합니다.
1. event 의 인스턴스를 생성한다.
2. raisedBy() 를 수행하며 VersionedAggregate 를 구현한 객체를 넘겨야 한다. 
3. raisedBy() 에서 header 값을 셋팅해준다.

불변 클래스로 만들지 않고 이런 과정을 거쳐야 하는 이유를 loom-core 사용자들은 알지 못하고, raisedBy 와 같은 프로세스는 학습이 필요하며 놓치기 쉽고 복잡하게 느껴질 수 있을거 같습니다.
 (도구를 사용하기 위해서 학습이 필요한건 사실이지만, 가능하면 학습을 최소화 시켜주는 것도 중요할거 같습니다.)

물론, 그런 복잡함을 대신 해결해주기 위해 AbstractAggregateRoot 와 AbstractDomainEvent 를 만들어서 제공해주는것이지만 AggregateRoot 인터페이스를 직접 implements 하는 경우에는 직접 구현해야 하는 부분이 됩니다.

이 부분에 대해서는 어떤 의견을 가지고 계신가요?

* 아래와 같은 코드가 될 수 있겠네요

``` java
public class Issue implements AggregateRoot, VersionedAggregate {
    // id, title..  pendingEvents...

    public void changeTitle(String title) {
        TitleChanged event = new TitleChanged(title);
        event.raisedBy(this);    // 누락하기 쉬움, VersionedAggregate 를 넘기는 것에 대한 이해 필요
        apply(event);
        this.pendingEvents.add(event);
   }

   public void apply(TitleChanged titleChanged) {
       this.title = titleChanged.getTitle();
   }
}

public class TitleChanged implements DomainEvent {
     private UUID id;
     private long version;
     private ZonedDateTime occurrenceTime;
     private String title;

    public TitleChanged(String title) {
         this.title = title;
    }

    // 구현시 raisedBy 의 역할과 VersionedAggregate 인터페이스에 대한 이해 필요
    public void raisedBy(VersionedAggregate versionedAggregate) {
          this.id = versionedAggregate.getId();
          this.version = versionedAggregate.getVersion() + 1;
          this.occurrenceTime = versionedAggregate.getOccurrenceTime();
   }

   // getter;
}
```

**Comment by mhyeon-lee** [comment]
다음과 같이 불변 클래스와 편의 클래스를 사용자가 선택할 수 있게 할 수 있는 디자인은 어떨까요?

``` java
public interface DomainEvent {
    UUID getAggregateId();
    long getVersion();
    ZonedDateTime getOccurrenceTime();
}

// 이름은 우선 대충 지었습니다.
public interface RaisableDomainEvent extends DomainEvent {
     void raisedBy(VersionedAggregate versionedAggregate);
}

public abstract class AbstractDomainEvent implements DomainEvent {
      private final UUID id;
      private final long version;
      private final ZonedDateTime occurrenceTime;

      protected AbstractDomainEvent(UUID id, long version, ZonedDateTime occurrenceTime) {
             this.id = id;
             this.version = version;
             this.occurrenceTime = occurrenceTime;
     }
     // only getter
}

 public abstract class AbstractRaisableDomainEvent  implements RaisableDomainEvent {
           private UUID id;
           private long version;
           private ZonedDateTime occurrenceTime;

          public void raisedBy(VersionedAggregate versionedAggregate) {
               this.id = versionedAggregate.getId();
               this.version = versionedAggregate.getVersion();
               this.occurrenceTime = ZonedDateTime.now();
          }

           // getter, setter
   }


public class AbstractAggregateRoot implements AggregateRoot, VersionedAggregate {
     // id ...

    void raise(DomainEvent event) {
          if (event instanceof RaisableDomainEvent) {
                 RaisableDomainEvent raisableEvent = (RaisableDomainEvent) event;
                 raisableEvent.raisedBy(this);
          }
          //  apply handler
          // pending event
    }
}
```

사용자는 아래와 같이 선택해서 사용할 수 있습니다.

1. raisedBy를 통한 dispatch 와 VersionedAggregate 가 뭔지 모르겠다. 
나는 조금 불편해도 불변 이벤트를 만들겠다.

``` java
    public class TitleChanged extends AbstractDomainEvent {
          private final String title;
      
          public TitleChanged(UUID aggregateId, long version, 
                     ZonedDateTime occurrenceTime, String title) {
             super(aggregateId, version, occurrenceTime, title);
         }
     
        // getter
    }
```

2. 나는 생성자를 통해서 매번 header 정보를 넘기는게 번거롭다.
불변이 아니어도 좋으니 편하게 사용하겠다.

``` java
    public class TitleChanged extends AbstractRaisableDomainEvent {
          private String title;
      
          public TitleChanged(String title) {
             super(aggregateId, version, occurrenceTime, title);
         }
     
        // getter
    }
```

이 도구를 사용하는 사용자에게는 이벤트 클래스에 대한 학습 여부 또는 취향에 따른 선택 옵션을 줄 수 있는 방법이 될거 같습니다.

**Comment by mhyeon-lee** [comment]
추가적인 의견이 나오지 않아 앞에 나왔던 여러 의견과 개인 의견을 종합해서 아래 PR 을 먼저 날려봅니다.
방향성이 큰 범위에서 벗어나지 않는다면 이 PR 리뷰를 중심으로 다듬어가면 어떨까 합니다.

- 의견 정리
    * DomainEvent 의 불변성을 강요하기에는 사용자들에게 고통을 준다.
    * 이벤트 header 정보 셋팅은 중요하지만 반복되면서 실수할 여지가 있으므로 프레임워크에서 처리해주면 좋겠다.
    * 이벤트의 도메인 정보와 Header 정보를 분리하는 것은 message-driven 방식에서 불리하다. #40 
    * Abstract 가 아닌 DomainEvent 인터페이스를 직접 구현할 경우 후처리로 header 정보 셋팅을 하게된 배경 및 후처리 프로세스에 대한 이해가 필요할 수 있다.
    * 정석대로 완전 불변 Event 를 만들고 싶은 사용자들에게는 DomainEvent 의 raise() api 는 불필요하다.
<br/>

-  PR 에서의 방향성 https://github.com/loom/loom-core/pull/46

    * 후처리 header setting 을 지원하고 initialized 됐는지 체크할 수 있도록 `DomainEvent` 를 확장하여  `LazyInitializedDomainEvent` 인터페이스를 만든다.
    * `LazyInitializedDomainEvent` 는 `afterHeaderPropertiesSets` API 를 제공하며, VersionedAggregate 를 받아 Header 정보를 후처리 셋팅할 수 있도록 한다.
    * `isInitialized` API 는 header 정보가 셋팅되어 있는지를 확인하며, `afterHeaderPropertiesSets` 에서는 `isInitialized` API 를 사용해 최초 초기화만 할 수 있도록 체크할 수 있다.

    * AbstractAggregateRoot 의 `raise` 메소드는 발생한 DomainEvent 를 받아 apply 후 pending 시킨다.
    * DomainEvent 가 `LazyInitializedDomainEvent` 를 구현했고, 아직 `initialized` 되지 않았다면, `afterHeaderPropertiesSets` 를 실행하여 DomainEvent 의 header 정보를 후처리로 셋팅한다.

**Comment by gyuwon** [comment]
@mhyeon-lee 말씀하신 방법의 방향은 이해했는데요, 별도의 인터페이스를 두기보다 `DomainEvent`에 기능을 추가하는 것은 어떨까요?

```java
public interface DomainEvent {
    boolean isRaised();
    void raise(VersionedEntity source);
}
```

덧붙여 #46 의 `VersionedAggregate`는 `VersionedEntity` 이름이 정체성을 더 잘 표현하지 않을까 싶습니다. `Entity`는 `getId()` 메서드를, `Versioned`는 `getVersion()` 메서드를 표현할 수 있고 인터페이스의 기능이 집합체 개념에 의존된 부분은 없기 때문에 그렇게 생각합니다. 그리고 이벤트 소싱이 적용된 집합체는 `VersionedEntity`가 가진 기능을 모두 필요로하고 개념적으로도 부분집합이니 상속관계를 두는 것이 자연스럽고요.

```java
public interface AggregateRoot extends VersionedEntity {
}
```

**Comment by mhyeon-lee** [comment]
두 종류의 인터페이스가 크게 역할 분담을 해야하는 건 아니기 때문에, `DomainEvent` 에 합쳐도 무리는 없겠군요.
다만 `DomainEvent` 인터페이스를 불변으로 직접 구현할때 `isRaised()` 와 `raise(VersionedEntity source)` 는 불필요하게 구현해줘야 하는 API 가 될거 같습니다.

아래와 같이 `default` 메소드를 만들어서 `raise` 를 필요로  할때 `override` 해서 구현하게 하는것은 어떨까요?

``` java
public interface DomainEvent {
      default boolean isRaised() {
            return true;
      }
      default void raise(VersionedEntity source) {
             throw new UnsupportedOperationException(".....");
      }
}
```

VersionedAggregate -> VersionedEntity,   그리고 AggregateRoot 가 VersionedEntity 를 상속하게 하는 방향은 합당하다고 생각합니다. 찬성합니다.

**Comment by gyuwon** [comment]
@mhyeon-lee `default`에 대해선 생각해 볼 거리네요. 다른 분들의 의견도 들어보고 싶네요. :)

**Comment by mhyeon-lee** [comment]
## 6/21 오프라인 논의 결정 내용

### 도메인 이벤트의 헤더 정보 분리 여부

#40 의 결정 사항에 따라 이벤트 클래스 및 메시지의 구조가 다르게 됩니다.
각 방식은 장단점이 있지만 loom 의 방향성을 고려해서 결정하는게 좋을거 같습니다.

이 이슈와 관련이 있듯이 이벤트의 불변 유지를 위해서는 loom 을 사용하는 개발자에게 불편함을 주며 실수를 유발할 수 있습니다. 그래서 불변성을 포기하고 후처리로 header 정보를 프레임워크가 처리할 수 있게 하자는 의견이 나왔었습니다.

불변성을 지키고 편의성을 제공해줄 수 있는 방법으로 이벤트 header 정보와 payload 를 분리하자는 제안이 나왔었습니다. 다만 이벤트 클래스 구조를 이렇게 분리했을 경우 이벤트 타입을 직접적으로 활용할 수 없다는 단점이 발생합니다. 또한 이러한 구조를 가진 이벤트는 이벤트 소싱을 위한 이벤트들로 별도 관리 및 컨트롤을 해줘야 합니다. (handler, serialize/deserialize 등)
이벤트 소싱을 위한 별도 관리 및 컨트를은 해당 메시지를 사용하는 쪽에서 알아야된다는 단점이 있지만, 반대로 알고 있다면 좀 더 컨트롤 하기 쉽고 프레임워크 레벨에서 편의 기능을 넣어주기도 쉽다는 장점도 됩니다.

이 논의 결정은 loom 의 방향성과 관련이 있습니다.

1. loom 을 axon 과 같이 이벤트소싱/CQRS 에 필요한 기능을 all-in-one 형태로 제공하면서 loom 을 사용하는 애플리케이션끼리의 호환을 쉽게 해주는 방향으로 가면 이벤트 header 와 payload 를 분리하는 구조가 유리합니다.

2. loom 을 해당 프레임워크에 종속시키는 것보다 다양한 플랫폼과의 호환도 가능하도록 유지하는데는 이벤트 타입이 payload 타입이 되도록 분리하지않는게 유리합니다. handler 도 별도 구현이 필요하지 않고 message 형태도 일반적인 형태로 교환할 수 있게 됩니다. 하지만 1번보다는 프레임워크 종속 편의 기능을 넣는데는 불편함이 있을거로 예상이 됩니다.

오프라인 회의에서 논의 결과 풍부한 기능 보다는 loom 사용자를 프레임워크에 종속시키지 않도록 가볍게 가면서 다른 플랫폼과의 호환을 자연스럽게 하는 방향이 더 좋겠다는 의견으로 2번 방향으로 가기로 결정했습니다.

@jaceshim @LeeKyoungIl 님도 참고하시고 추가 질문이나 의견주시면 감사하겠습니다.

**Comment by mhyeon-lee** [comment]
이벤트 클래스 header 와 payload 를 분리하지 않기로 결정하면서 자연스럽게 불변도 컴파일 레벨에서 유지하는건 포기하는 방향으로 갑니다.

@gyuwon 님의 이 이슈 제안대로 후처리로 셋팅하는 방향으로 가고 이 이슈는 닫습니다.
