### ISSUE TITLE
이벤트의 도메인 정보와 헤더 정보 분리

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#40]
이 이슈는 이슈 #37 과 밀접하게 관련됩니다.

### 도메인 정보와 헤더를 분리한 불변 디자인

제가 처음 .NET에서 이벤트 소싱을 구현하면서 도메인 이벤트를 설계할 때, 당연이 불변성에 대해 고려했고 도메인 정보와 이벤트 소싱 헤더 정보 분리를 생각했습니다.

```csharp
public sealed class DomainEvent
{
    public DomainEvent(
        Guid sourceId,
        int version,
        DateTimeOffset raisedAt,
        object payload)
    {
        // Guard clauses here.

        SourceId = sourceId;
        Version = version;
        RaisedAt = raisedAt;
        Payload = payload;
    }

    // Header properties
    public Guid SourceId { get; }
    public int Version { get; }
    public DateTimeOffset RaisedAt { get; }

    // Domain data
    public object Payload { get; }
}

public abstract class EventSourced
{
    private readonly Guid _id;
    private int _version;
    private List<DomainEvent> _pendingEvents;

    public Guid Id => _id;
    public int Version => _version;

    protected void RaiseEvent(object eventPayload)
    {
        _pendingEvents.Add(new DomainEvent(_id, ++_version, DateTimeOffset.Now, eventPayload));
    }
}

public sealed class UsernameChanged
{
    public UsernameChanged(string username)
    {
        Username = username;
    }

    public string Username { get; }
}

public sealed class User
{
    public void ChangeUsername(string username)
    {
        // Guard clauses here.

        RaiseEvent(new UsernameChanged(username));
    }
}
```

이벤트 소싱 인프라 추상 계층과 도메인 계층 관점에서만 보면 군더더기 없는 디자인입니다.

### 메시지 중심(Message-Driven)

그런데 저는 이벤트 소싱 패턴의 범위 안에서만 디자인을 고민하지 않았고 메시지 중심 아키텍처 관점에서 고민했습니다. 메시지 중심 디자인은 반응형 시스템([http://www.reactivemanifesto.org/](http://www.reactivemanifesto.org/))의 기반이고 이벤트 소싱 패턴은 메시지 중심 디자인과 잘 어울립니다. 그리고 이벤트 소싱을 사용할 때 주의할 점으로 공통적으로 꼽는 하나는 시스템 전체를 이벤트 소싱으로 뒤덮지 않는 것입니다. 시스템의 구성요소 중 이벤트 소싱이 유용한 곳에만 적용하는 것이 좋습니다.

따라서 저는 반응형 시스템을 관통하는 메시징 인프라와 이벤트 소싱 구현체를 구분하려 했고 후자가 전자에 의존하는 구조를 설계했습니다. 결과적으로 Khala 프로젝트는 [Khala.Messaging](https://github.com/Reacture/Khala.Messaging)과 [Khala.EventSourcing](https://github.com/Reacture/Khala.EventSourcing)으로 분리되었습니다.

반응형 시스템 구성요소 중 이벤트 소싱을 사용하는 것들과 그렇지 않은 것들 모두 동일한 메시징 인프라를 통해 소통하게됩니다. 이벤트 소싱을 사용하는 서비스에서 발행되는 이벤트와 이벤트 소싱을 사용하지 않는 서비스에서 발송되는 명령이 공유된 메시징 도구를 통해 흐릅니다. 그런 이유로 Khala 프로젝트는 이벤트 소싱 못지 않게 메시징 도구를 중요하게 다룹니다.

### 메시지 처리기

이벤트 수신자 입장에서 이벤트는 말 그대로 이벤트일 뿐 저장 수단은 아닙니다. 명령도 이벤트도 동일한 인터페이스를 통해 소비됩니다.

```csharp
public interface IMessageHandler
{
    void HandleMessage(object message);
}
```

메시지 처리기 구현체는 `message` 형식을 기준으로 논리를 분기합니다. `ChangeUsername` 명령이 전달될 수도있고 `UsernameChanged` 도메인 이벤트가 전달될 수도 있습니다. 메시지 처리기의 논리를 매번 직접 구현한다면 다음과 같은 코드가 반복될 것입니다.

```csharp
public class CommandHandler : IMessageHandler
{
    public void HandleMessage(object message)
    {
        if (message is CreateUser)
        {
            Handle((CreateUser)message);
        }
        else if (message is ChangeUsername)
        {
            Handle((ChangeUsername)message);
        }
        else ...
    }

    private void Handle(CreateUser command) { ... }
    private void Handle(ChangeUsername command) { ... }
}
```

이런 반복 작업을 줄여 생산성과 안정성을 높이기 위해 [Khala.Messaging](https://github.com/Reacture/Khala.Messaging) 프로젝트는 `InterfaceAwareHandler` 클래스를 제공합니다. 이 클래스를 이용하면 메시지 핸들러는 인터페이스를 통해 메시지 분기를 처리할 수 있습니다.

```csharp
public class CommandHandler :
    InterfaceAwareHandler,
    IHandles<CreateUser>,
    IHandles<ChangeUsername>
{
    public void Handle(CreateUser command) { ... }
    public void Handle(ChangeUsername command) { ... }
}
```

그런데 만약 도메인 이벤트가 처음 소개된 것과 같이 디자인되었다면 모든 도메인 이벤트는 `DomainEvent` 형식으로 전달됩니다. 메시지 개체의 형식을 기준으로 논리를 분기하기 어렵습니다.

### Polyglot

`DomainEvent.Payload` 속성을 기준으로 분기하는 도메인 이벤트 전용 메시지 처리기 기반 클래스를 만드는 대안을 생각할 수 있습니다. 그런데 저는 둘 이상의 언어로 개발된 분산 시스템을 떠올렸을 때 이것은 좋은 선택이 아니라고 판단했습니다.

Node.js로 개발된 서비스가 .NET으로 개발된 서비스의 도메인 이벤트를 수신하는 경우를 고려해보죠. 메시지 중개자는 메시지 본문과 더불어 기타 속성을 함께 전달할 수 있습니다. 이 때 원본 메시지의 강력한 형식 이름을 속성에 담는 것은 유용합니다. JavaScript로 작성된 메시지 처리기는 메시지의 강력한 형식 이름을 통해 논리를 분기할 수 있을 것입니다. 그런데 다양한 도메인 이벤트가 모두 `Khala.EventSourcing.DomainEvent`라는 형식의 이름으로 전달된다면 Node.js로 개발된 메시지 소비자는 곤란함에 빠집니다.

저는 가능하면 우리 프로젝트 결과물이 Java로 뒤덮인 시스템에서만 유용하도록 하고싶지 않습니다.

### 결론

물론 이 문제 또한 디자인에 복잡한 규칙들을 추가해 해결할 수 있을 겁니다. 그런데 도메인 이벤트의 물리적 불변성 확보가 이 모든 것들의 희생을 치를만큼 가치를 가지는가 하는 의문이 생깁니다. 이론적으로 이벤트 소싱의 이벤트 저장소는 변경과 삭제가 없고 추가만 있습니다. 그런데 물리적으로도 그런가요? SQL 데이터베이스에 구축된 이벤트 저장소는 `UPDATE` 명령과 `DELETE` 명령을 차단하나요? 우리는 이벤트 소싱을 위해 변경과 삭제가 없는 데이터베이스부터 만들어야 하나요?

저는 Khala 프로젝트를 개발하면서 이슈 #37 의 내용과 같이 물리적 불변성을 포기하는 선택을 했습니다. 제 역량이나 노력이 부족해 아직 좋은 해결책을 찾지 못한 것일 수도 있습니다. 이슈 #37 과 마찬가지로 논의를 통해 더 좋은 방안을 도출할 수 있기를 바랍니다. 많의 의견 부탁드립니다. :)

**Comment by jaceshim** [comment]
@gyuwon 
좋은 지식공유 감사드립니다~

Message Driven 기반하에
이벤트소싱에 의한 메세지와 그렇지 않은 일반적인 메세지를 Message  Broker의 topic으로 분리하여 발행하면 해결될 수 있긴 하겠지만 이 또한 framework의 지원 사항이 아닌 사용자들의 유도리에 맡겨야 하는 부분이라 문제가 될수있겠군요...

polyglot 환경에서 메세지를 범용적으로 사용할수 있게 하려면 오히려 순수 json 타입이 맞지 않나 싶은데 어떻게 생각하신지요? 순수 json타입의 경우 일전에 규원님이 말씀하신 발생된 이벤트 타입(동사)을 잃어 버린다는 문제가 있었는데요... 순수 json을 사용하지 않으면 polyglot환경 대처가 사실상 불가능 하지 않을까요?
또한 직렬화시에 해당 메세지에 대한 타입을 명시한다 해도 역직렬화 과정에서 타입에 대한 사전인지가 불가능하면
일반적인 map형태로 일단 역직렬화 한다음에 거기서 타입이 명시된 속성을 기준으로 다시한번 해당 타입으로 재 생성을 해야 하는 불편함이 존재 할것 같다는 생각이 듭니다

규원님 의견 읽어보니 저도 메세지 중심적 처리가 좋을것 같다고 생각되는데요 넘어야할 산이 조금 많은것 같습니다

**Comment by LeeKyoungIl** [comment]
@gyuwon @jaceshim 
"Java로 뒤덮인 시스템에서만 유용하도록 하고싶지 않습니다."  매우 좋습니다. 우리가 가야할 방향 이라고 생각합니다.

하지만 역시 polyglot환경을 대응 하자면 역시 Json 타입 말고는 방법이 없다고 생각이 되는데요. 
역 직렬화 과정에서 타입에 관해 사전 인지가 불가능 한것이 문제 인데요. json 타입 기반으로 loom만의 직렬화 라이브러리를 만들고 주요 언어를 대상으로 역직렬화 라이브러리는 제공하는 것은 어떨까요?

**Comment by gyuwon** [comment]
@jaceshim @LeeKyoungIl 저도 지금 시점에 메시징을 위해 JSON 사용이 가장 좋다고 생각합니다. 이 부분에 대해서는 전혀 이견이 없습니다. 하지만 두 분 말씀처럼 메시지의 동사를 잃어버리는 문제점이 있죠. 그래서 메시지 전달에 동사를 포함시킬 수단이 필요합니다. 아마 Java 프로그램 사이에서는 쉽게 동사 유지가 될겁니다. Java를 위한 JSON 직렬화 도구가 쉽게 처리해주지 않을까 싶어요.(이 부분에 대해서 이슈 #10 에서 @jaceshim 님께 확인을 부탁드렸습니다.)

여기에 더해 이종 플랫폼 기반의 서비스에 메시지를 보낼 때 동사를 유지할 수단에 대해 말씀드리는데, 이 때 이 수단이 이벤트 소싱에 종속되지 않으면 더 좋지 않을까하는 바램이 있는 것입니다. 위 도메인 이벤트 구현의 경우는 메시징 도구가 `DomainEvent.Payload` 속성에 대해 알아야만 동사를 알아낼 수 있고 메시지 수신자 역시 마찬가지입니다.

```csharp
public class MessageBus
{
    private readonly IMessageSerializer _serializer;
    private readonly IMessageBroker _broker;

    public void SendMessage(object message)
    {
        // Guard clauses here.

        string body = _serializer.Serialize(message);
        var envelope = new Envelope(body);

        if (message is DomainEvent) // I hate this!
        {
            envelope.Properties["MessageType"] = ((DomainEvent)message).Payload.GetType(); // I hate this, too!
        }
        else
        {
            envelope.Properties["MessageType"] = message.GetType(); // Reasonable.
        }

        _broker.Send(envelope);
    }
}
```

만약 메시지 개체의 강력한 형식 자체가 동사라면 메시징 도구와 메시지 수신자는 이러한 정보에 대해 알 필요가 없습니다. 즉, 이벤트 헤더 속성을 갖는 메시지 개체(`DomainEvent`)와 도메인 정보를 담은 개체(`IssueCreated`)가 has-a 관계가 아니라 is-a 관계라면 메시징 인프라는 이벤트 소싱에 대해 종속적이지 않습니다.

**Comment by mhyeon-lee** [comment]
https://github.com/loom/loom-core/issues/10
https://github.com/loom/loom-core/pulls 와 관련됩니다.

**Comment by jwChung** [comment]
1. 이벤트헤더 정보는 프레임워크에서 자동으로 처리하는 주는 것이 좋겠다.
2. 직렬화 시 강력한 이름 형식이 포함되었으면 좋겠다. if-else 문제를 피하기 위해
3. 맨위 HAS-A관계로 처리하면 1번은 깔끔하게 해결되는데 2번 처리가 어렵다.
4. 그래서 3번으로 취할 수 있는 불변성 확보를 포기하고 IS-A관계로 1, 2번을 처리하는 것이 어떻겠냐.

#39, #40 으로 이어지는 이슈를 제가 이해한데로 위와 같이 정리했습니다. 제가 문맥을 잘 따라 왔나요.

**Comment by mhyeon-lee** [comment]
@jwChung 네 정리해주신 사항에 이어서 https://github.com/loom/loom-core/issues/37#issuecomment-300530144 여기에 우려점과 의견을 남겼습니다.

**Comment by mhyeon-lee** [comment]
> 따라서 저는 반응형 시스템을 관통하는 메시징 인프라와 이벤트 소싱 구현체를 구분하려 했고 후자가 전자에 의존하는 구조를 설계했습니다. 결과적으로 Khala 프로젝트는 Khala.Messaging과 Khala.EventSourcing으로 분리되었습니다.

@gyuwon 님이 위와 같은 이유로 프로젝트를 구분했는데 loom 도 messaging 은 loom-messaging 으로 분리하는 전략이 괜찮아 보입니다. loom-core 로 시작한 이유도 분리 가능한 repo 는 분리하려고 만든 의도이기도 했고요

--

분리하더라도 최상위 serializer 인터페이스는 core 에 있는게 좋겠다는 생각이 듭니다.

**Comment by gyuwon** [comment]
만약 도메인 이벤트의 불변성을 포기할 경우 실제 코드는 어떨지 생각해 봤으면 합니다. C#의 경우 속성은 언어의 많은 지원을 받습니다. Khala.EventSourcing을 사용해 도메인 이벤트를 발생시키는 코드는 예를 들면 다음과 같습니다.

```csharp
public void SupplySku(string skuDiscriminator, int stockQuantity, Price totalNetPrice)
{
    // Guard clauses here.

    RaiseEvent(new SkuSupplied
    {
        SkuDiscriminator = skuDiscriminator,
        StockQuantity = stockQuantity,
        TotalNetPrice = totalNetPrice
    });
}
```

Java의 경우 속성을 사용한 초기화 식을 사용할 수 없기 때문에 생성자를 이용해야 합니다.

```java
public void supplySku(String skuDiscriminator, int stockQuantity, Price totalNetPrice) {
    // Guard clauses here.

    raiseEvent(new SkuSupplied(
            skuDiscriminator,
            stockQuantity,
            totalNetPrice));
}
```

그런데 이 경우 JSON 직렬화기가 도메인 이벤트를 역직렬화할 때 헤더 정보를 누락시키게 되는 치명적인 문제가 발생합니다. 따라서 조금 번거롭지만 이렇게 해야합니다.

```java
public void supplySku(String skuDiscriminator, int stockQuantity, Price totalNetPrice) {
    // Guard clauses here.

    SkuSupplied skuSupplied = new SkuSupplied();
    skuSupplied.setSkuDiscriminator(skuDiscriminator);
    skuSupplied.setStockQuantity(stockQuantity);
    skuSupplied.setTotalNetPrice(totalNetPrice);

    raiseEvent(skuSupplied);
}
```

어쩌면 Java 프로그래머 입장에서 별로 번거롭지 않다고 느껴질 수도 있습니다만 한번쯤 생각은 해봤으면 해서 말씀드립니다.

**Comment by mhyeon-lee** [comment]
@gyuwon 
AbstractAggregateRoot 에서 header 정보들에 대한 setter 를 default-package level 로 정의해 놓으면 역직렬화시 값을 셋팅해주는 것으로 알고 있습니다.

그래서 역직렬화시 생성자를 통해서 payload 값을 셋팅한 후 후처리로 setter 를 통해 header 정보가 셋팅될 것으로 예상됩니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 제가 정확히 이해하기 못하겠네요. 코드는 어떻게 될까요?

**Comment by mhyeon-lee** [comment]
@gyuwon 네 제가 jackson 의 동작 위주로만 커멘트를 적어놨네요
아래와 같이 사용 가능할 것으로 보입니다.

``` java
public abstract class AbstractDomainEvent implements DomainEvent {
    private UUID aggregateId;
    private long version;
    private ZonedDateTime occurrenceTime;

    protected AbstractDomainEvent() {
    }
   
    public void raise(VersionedEntity versionedEntity) {
          this.aggregateId = versionedEntity.getId();
          this.version = versionedEntity.getVersion();
          this.occurrenceTime = ZonedDateTime.now();
    }

    void setAggregateId(UUID aggregateId) {
          this.aggregateId = aggregateId;
     }
   
     void setVersion(long version) {
          this.version = version;
     }

     void setOccurrenceTime(ZonedDateTime occurrenceTime) {
          this.occurrenceTime = occurrenceTime;
     }

    public UUID getAggregateId() {
        return this.aggregateId;
    }

    public long getVersion() {
        return this.version;
    }

    public ZonedDateTime getOccurrenceTime() {
        return this.occurrenceTime;
    }
}

public class IssueCreated extends AbstractDomainEvent {
    private final String title;
    private final String body;
   
    @ConstructorProperties({"title", "body"})
    public IssueCreated(String title, String body) {
        this.title = title;
        this.body = body;
    }

    public String getTitle() {
        return this.title;
    }

    public String getBody() {
        return this.body;
   }
}
```

IssueCreated 클래스는 생성자만으로 serialize/deserialize 가 가능합니다.

> 실제 테스트를 돌려보니까 AbstractDomainEvent 에 setter 가 없어도 deserialize 시에 값을 잘 셋팅해주네요

**Comment by jaceshim** [comment]
@mhyeon-lee @gyuwon 
 궁금한게 있는데요 헤더정보에 Event Type이 기술되지 않고 있는데요
이 경우 payload로 serialize된 Object Type을 어떻게 유추 할 수 있을까요?

**Comment by mhyeon-lee** [comment]
@jaceshim 
https://github.com/loom/loom-core/pull/43/files#diff-3d29f815d0b1b4aa80e4fa901fd0f6e6R57

여기를 보면 event 객체를 json 으로 serialize 하면서 `@type` 으로 해당 클래스 정보를 포함하게 되는데 이걸 질문하신 건가요?

**Comment by mhyeon-lee** [comment]
이 이슈도 이벤트 헤더와 payload 를 분리하지 않기로 결정하면서 닫겠습니다.

추가 논의나 의견이 필요하면 다시 열면 되겠습니다.

**Comment by jaceshim** [comment]
@mhyeon-lee
type속성을 기술하는것으로 fix되었다면 제 질문은 의미가 없어지는것 같습니다.

이벤트 수신자들의 instanceof 압박이 걱정되긴 합니다. ㅡㅡ

**Comment by mhyeon-lee** [comment]
@jaceshim 아 헤더와 payload 를 분리했을때에 대한 질문이시군요

**Comment by mhyeon-lee** [comment]
@jaceshim 핸들러를 구현할때 어떻게 해줄지 고민해봐야 겠군요
