### ISSUE TITLE
AbstractDomainEvent 생성자중 occurrenceTime값을 받지 않는 생성자 추가

### ISSUE THREAD

**Issue by jaceshim** [loom/loom-java#42]
`protected AbstractDomainEvent(UUID aggregateId, long version) {
        this(aggregateId, version, ZonedDateTime.now());
    }

    protected AbstractDomainEvent(UUID aggregateId, long version, ZonedDateTime occurrenceTime) {
        if (aggregateId == null) {
            throw new IllegalArgumentException("The parameter 'aggregateId' cannot be null.");
        }
        if (version < 1) {
            throw new IllegalArgumentException("The parameter 'version' must be greater than 0.");
        }
        if (occurrenceTime == null) {
            throw new IllegalArgumentException("The parameter 'occurrenceTime' cannot be null.");
        }

        this.aggregateId = aggregateId;
        this.version = version;
        this.occurrenceTime = occurrenceTime;
    }`

위 코드처럼  사용자가 매번 `DomainEvent` 를 생성시 occurrenceTime값을 넘겨주는 불편함을 해소하고자
occurrenceTime을 받지 않는 생성자를 추가하는것에 대해 발생할 수 있는 side effect나 기타 의견을 듣고자 합니다.
[https://github.com/loom/loom-core/pull/41](url)

**Comment by gyuwon** [comment]
우연히도 제가 어제 페북에 공유한 켄트 벡의 디자인 규칙들이 생각납니다. :)

https://martinfowler.com/bliki/BeckDesignRules.html

- 테스트 통과(Passes the tests)
- 의도 노출(Reveals intention)
- 중복 제거(No duplication)
- 최소한의 요소(Fewest elements)

이 중 `최소한의 요소`는 우선순위가 가장 낮습니다. 여기서 우선순위가 낮다는 것은 중요하지 않음을 의미하는 것이 아니라 가장 수준 높은 디자인을 위해 고려함을 뜻합니다. 우리는 범용 라이브러리 혹은 프레임워크를 만들고 있기 때문에 이 규칙을 자주 떠올릴 필요가 있다고 생각합니다.

이 규칙에 대한 마틴 파울러의 설명은 이렇습니다.

> The last rule tells us that anything that doesn't serve the three prior rules should be removed. At the time these rules were formulated there was a lot of design advice around adding elements to an architecture in order to increase flexibility for future requirements. Ironically the extra complexity of all of these elements usually made the system harder to modify and thus less flexible in practice.

즉, 앞의 3가지 규칙을 위한 것이 아니라면 모두 제거하라는 것이죠. 아직 드러나지 않은 요구사항에 대응하기 위해 새로운 요소들을 추가하는 것이 결과적으로 시스템에 나쁜 영향을 끼치기 때문입니다.

저는 `AbstractDomainEvent` 클래스에 `occurrenceTime` 매개변수가 빠진 생성자를 추가하는 것이 아직 충분히 드러나지 않은 요구사항에 조금은 성급히 대응하는 것으로 느껴집니다.

다른 분들의 의견도 기다립니다. :)

**Comment by jaceshim** [comment]
좋은글입니다~
최대한 위 규칙을 따르도록 하는게 좋을것 같아요~
다만 제가 생성자를 추가한 의도는 드러나지 않은 요구사항을 사전에 도출한 의미보단 제가 공부하면서 봐온 몇몇 오픈소스들에서 발생일시를 framework단에서 처리하고 있었기에 분명 그런식의 처리의 이유가 있을것 같았고 그 이유로 매번 반복적인 작업을 framework을 사용하는 개발자가 전달해야 함을 없애기 위해 지원 하는걸로 나름 해석 했었습니다. 하지만 loom의 경우 제가 봐온 여타 framework의 java base 직렬화기와는 다른 컨셉의 직렬화기를 고려하고 있기에 현시점에선 필요치 않고 이는 파울러 횽님의 최소한의 요소 규칙에 어긋나는것 같습니다. :-)

**Comment by mhyeon-lee** [comment]
이 이슈도 우선은 닫고 추후에 필요해질때 열도록 하겠습니다.
