### ISSUE TITLE
AggregateRoot 와 DomainEvent 의 Serializable 인터페이스 확장

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#44]
현재 AggregateRoot 와 DomainEvent 인터페이스는 Serializable 인터페이스를 확장하고 있습니다.
@jaceshim 페이스북에서 박성철님께서 DomainEvent 는 왜 Serializable 을 확장하는지 질문을 주셨었는데요
https://www.facebook.com/jaceshim.kr/posts/10155376052964407?comment_id=10155376073989407&reply_comment_id=10155376149094407&comment_tracking=%7B%22tn%22%3A%22R%22%7D

다시 생각해보니 현 시점에서는 DomainEvent 가 Serializable 을 확장할 필요가 없을거 같군요
특정 언어나 기술에 종속되지 않는 메시지를 만드는 목표에도 java 의 Serializable 인터페이스는 부합되지 않는거 같고요.

그래서 필요성이 생길때까지 DomainEvent 에 Serializable 확장을 제외하고자 합니다.

* AggregateRoot 에 Serializable 도 필요없어서 같이 제거하고자 합니다.

**Comment by gyuwon** [comment]
`AggregateRoot` 클래스는 확실히 필요 없을 것 같네요. `DomainEvent`의 경우는 다른 분들께 넘기겠습니다.

**Comment by jaceshim** [comment]
@mhyeon-lee
네 그런 의도라면 제거해도 좋을것 같습니다~
