### ISSUE TITLE
core 에서 Message 직렬화기 구현체(Jackson) 내장 여부

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#48]
@gyuwon 님이 작성한 https://github.com/loom/loom-core/pull/47 에서 `MessageSerializer` 인터페이스와 함께 구현체(Jackson)가 함께 내장됐습니다. 

repo 이름을 `loom-core`로 한 것은 인터페이스와 특정 기술에 의존하는 구현체를 repo 에서 분리하기 위한 목적도 있었습니다. 그래서 jackson 구현체 같은 경우는 `loom-message-jackson` 과 같은 형태로 분리될 수 있습니다.

@gyuwon 님께서는 아래와 같이 의견을 주셨습니다.
> 저는 직렬화기 인터페이스와 기본 구현체를 함께 제공하는 것이 어떨까 생각하는데 이후 논의를 통해 구현체를 분리하는 것도 고려해볼 수 있겠습니다.

구현체(Jackson) 의 core 내장 여부에 관한 의견을 모으고자 합니다.

**Comment by mhyeon-lee** [comment]
Integration 을 고려하면 Message 직렬화/역직렬화는 중요한 문제이기 때문에, 특정 구현체와 메시지 형식을 권장하는 것도 괜찮을거 같다는 생각이 듭니다.

java 생태계에 json serializer 기술이 분산되어 있는 것도 아니기 때문에, jackson 을 내장하는데 크게 거부감을 가지진 않을거 같습니다.

분리해야할 이유가 아직 없고, 개발 편의성을 고려해서 내장 해도 좋을거 같습니다.

**Comment by jaceshim** [comment]
저도 일부 범용적인 직렬화구현체는 포함되는게 맞다고 봅니다. 사실 이전에 core패키지에 특성중 의존성 배제 부분은 가급적 사용하지 말자는거지 특정 기술셋의 구현체가 포함되면 안된다는것은 아니였습니다
core패키지는 loom을 통해 이벤트 소싱을 구현하게 될 경우 필요한 필수 구현체의 성격으로 봐야 할것같습니다.

**Comment by gyuwon** [comment]
이 문제는 사용자 편의성과 jackson이 가지는 Java 생태계의 위상이 주요 변수가 되겠네요. 사용자 편의를 위해서는 확장성과 함께 기본 구현체가 제공되면 유익할 것이고 반면 jackson 패키지 종속을 달갑지 않게 생각하는 경우를 무시할 수 없다면 분리하는 것이 좋을 듯 하고요.

**Comment by mhyeon-lee** [comment]
저는 jackson 외에 다른 serializer 를 사용해보지 않아서 잘 모르겠습니다.

혹시 gson 이나 다른 serializer 를 애용하시는 분이 있다면, 사용하려는 프레임워크/라이브러리에 jackson 이 기본 내장 되어있을때의 기분을 들어보고 싶군요

**Comment by mhyeon-lee** [comment]
@LeeKyoungIl @jwChung @enshahar 
관련해서 의견 있으시면 주시면 좋을거 같아요

**Comment by mhyeon-lee** [comment]
이 부분도 특별히 반대 의견이 없으므로 닫겠습니다.
다른 이견이 있거나 다시 이 이슈 논의가 필요할때 열면 되겠습니다.
