### ISSUE TITLE
Message 표식 인터페이스

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#49]
`MessageSerializer` 인터페이스는 직렬화 대상 형식으로 `java.lang.Object`을 사용합니다. 기능적으로는 문제가 없습니다. 하지만 메시지로 다뤄질 수 있는 형식을 명시적으로 제한하기 위해 `Message` 표식(marker) 인터페이스 도입이 제안되었습니다.(#47 참고) `Message` 인터페이스는 이후 `MessageBus` 인터페이스나 `MessageHandler` 인터페이스에도 사용될 수 있습니다.

```java
public interface Message {
}

public interface MessageSerializer {
    String serializer(Message message);
}

public interface MessageBus {
    void Send(Message message);
}

public interface MessageHandler {
    void Handle(Message message);
}
```

**Comment by gyuwon** [comment]
개인적으로 `Message` 도입이 크게 필요하다고 생각하진 않습니다. 그렇지만 굳이 반대하는 입장이지도 않습니다.

**Comment by mhyeon-lee** [comment]
여기에서 `Message` 인터페이스는 기능에 대한 명세 보다는 `Serializable` 과 같은 `Marker` 인터페이스에 가까울 거 같습니다. (아직까지는)

`Marker` 인터페이스를 사용할지 결정하기 전에 MessageSerializer 는 어떤 타입을 지원하고 지원하지 않을지도 결정되면 좋을거 같습니다.

* Iterable
* Optional
* primitive
* enum

아마도 위의 타입들은 지원 하지 않고 Exception 을 throw 해야되지 않을까 싶습니다.

**Comment by gyuwon** [comment]
@mhyeon-lee Java에서 `enum`이 `java.lang.Object`인가요?

**Comment by mhyeon-lee** [comment]
@gyuwon  `java.lang.Object` 를 상속하고 있군요
https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html

**Comment by gyuwon** [comment]
@mhyeon-lee 위에서 나열하신 형식 방어에 대한 별도의 이슈를 만들어주실 수 있을까요?

**Comment by mhyeon-lee** [comment]
@gyuwon 별도 이슈로 생성했습니다.
https://github.com/loom/loom-core/issues/52

**Comment by mhyeon-lee** [comment]
표식 인터페이스를 추가하면 타입체크가 좀 더 편해지는 장점이 있지만, 스펙이 늘어나는 단점도 생기므로 현 단계에서는 Object 로 진행하고

진행하면서 black-list 로 타입 체크가 어려운 점이 생기거나 표식 인터페이스가 더 나은 장점을 줄 수 있을때 전환하는게 어떨까 합니다.

**Comment by jaceshim** [comment]
현 시점에서 메세지 타입을 Object 로 유지하는거에 동의 합니다.

**Comment by gyuwon** [comment]
두 분의 의견이 그러시니 일단 이 이슈는 닫겠습니다.

**Comment by mhyeon-lee** [comment]
@gyuwon 님께서 여기서 Mark 인터페이스는 우선 추가한 후에 추후에 필요가 없어지면 제거하는게 호환성 유지 측면에서 유리하다는 의견을 주셔서 다시 열었습니다.
