### ISSUE TITLE
코드 커밋 정책

### ISSUE THREAD

**Issue by jwChung** [loom/loom-java#5]
#2 의  **코드 커밋 절차** 와는 별개로, PR이 작성되면 이걸 승인하고 master로 병합하는 정책이 필요합니다. 가령 *core 멤버 2 명 이상 승인이 필요 하고, 이견(request changes)은 없어야 한다* 이런 식의 정책이 있을 수 있습니다.

**Comment by jwChung** [comment]
생각해보니  코드 커밋 절차 가 결정된 후 논의하는 것이 좋겠네요. 우선 이슈 닫아 놓겠습니다.

**Comment by mhyeon-lee** [comment]
https://github.com/loom/loom-core/issues/2  여기에 이어 커밋 정책을 정해봅니다.

현재 큰 틀은 아래와 같이 진행되는거 같습니다.

* new branch and coding
* pull request and request review
* review and approve
* merge to master

추가/조정 의견 있으시면 남겨주시고, 좀 더 디테일한 규칙들을 의견 주셔도 될거 같습니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 승인 조건만 추가하면 될 듯 하네요.

**Comment by mhyeon-lee** [comment]
저희 팀에서는 보통 리뷰어 중 한명 이상이 approve 하면 merge 합니다.
아직 리뷰를 못한 사람들은 이후에 merge된 PR 에 추가로 리뷰 의견을 달고 수정이 필요할 경우 별도의 수정 PR 을 다시 올립니다.

리뷰 승인 조건에 따라 코드 품질과 개발 속도 가 서로 영향을 미치므로 적절한 밸런스를 맞추는게 중요한거 같긴합니다.

**Comment by gyuwon** [comment]
@jwChung 님의 예시처럼 핵심 인원 2명의 승인으로 시작해보는 것이 어떨까요?

**Comment by jwChung** [comment]
@gyuwon 님 의견에 찬성 한표요.

**Comment by mhyeon-lee** [comment]
👍

**Comment by enshahar** [comment]
이제야 각 논의 스레드를 쫓아가기 시작했습니다. 한국서 손님이 오시는 바람에.. 한 1.5주일 정신이 없었네요. 

2명 승인으로 시작하면 될것 같습니다.

**Comment by jwChung** [comment]
2명 승인으로 시작하시죠.

@LeeKyoungIl, @jaceshim 님 위 정책 확인해주세요. 이 이슈는 닫도록 하겠습니다.

**Comment by jaceshim** [comment]
확인완료

**Comment by LeeKyoungIl** [comment]
확인 완료 ! @mhyeon-lee 한명 이상이 approve 하면 merge하셨군요. 제가 네이버에서 있던 팀에서는 DL님이 무조건 리뷰&승인&머징 까지 했었는데...

**Comment by mhyeon-lee** [comment]
@LeeKyoungIl 
아 현재 저희팀은 신규 프로젝트 개발 진행중이라 개발속도를 높이기 위해서 현재 그렇게 진행하고 있습니다.
릴리즈 후에는 좀 더 엄격하게 진행할거 같습니다.
