### ISSUE TITLE
MessageSerializer 의 미지원 타입 결정

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#52]
현재 MessageSerializer 는 Serialize/Deserialize 시 Object 를 사용하고 있습니다.

serialize/deserialize 를 지원할 수 없는 타입을 지정하고, 방어 코드를 작성해야 합니다.

* Iterable
* Optional
* primitive (wrapper)
* enum

기본적으로 다음 타입은 지원하지 않을거 같습니다.
그외에 생각나는 타입이나 다른 의견이 있으면 남겨주세요

**Comment by mhyeon-lee** [comment]
`Map` 타입은 지원하는게 좋을지 고민이 되네요. 
Serializer 입장에서 봤을때는 제한할 필요는 없을거 같은데,  EventStore 와 연계할때는 어떨지 고민해봐야겠네요

**Comment by jaceshim** [comment]
`public interface Message<T> extends Serializable {

    /**
     * Returns the identifier of this message. Two messages with the same identifiers should be interpreted as
     * different representations of the same conceptual message. In such case, the meta-data may be different for both
     * representations. The payload <em>may</em> be identical.
     *
     * @return the unique identifier of this message
     */
    String getIdentifier();

    /**
     * Returns the meta data for this event. This meta data is a collection of key-value pairs, where the key is a
     * String, and the value is a serializable object.
     *
     * @return the meta data for this event
     */
    MetaData getMetaData();

    /**
     * Returns the payload of this Event. The payload is the application-specific information.
     *
     * @return the payload of this Event
     */
    T getPayload();

    /**
     * Returns the type of the payload.
     * <p/>
     * Is semantically equal to {@code getPayload().getClass()}, but allows implementations to optimize by using
     * lazy loading or deserialization.
     *
     * @return the type of payload.
     */
    Class<T> getPayloadType();

    /**
     * Returns a copy of this Message with the given {@code metaData}. The payload remains unchanged.
     * <p/>
     * While the implementation returned may be different than the implementation of {@code this}, implementations
     * must take special care in returning the same type of Message (e.g. EventMessage, DomainEventMessage) to prevent
     * errors further downstream.
     *
     * @param metaData The new MetaData for the Message
     * @return a copy of this message with the given MetaData
     */
    Message<T> withMetaData(Map<String, ?> metaData);

    /**
     * Returns a copy of this Message with it MetaData merged with the given {@code metaData}. The payload
     * remains unchanged.
     *
     * @param metaData The MetaData to merge with
     * @return a copy of this message with the given MetaData
     */
    Message<T> andMetaData(Map<String, ?> metaData);
}
`

Axon의 Message Interface를 참고용으로 올립니다.

**Comment by mhyeon-lee** [comment]
Axon 의 이벤트는 header 와 payload 가 분리되어 있어서 이러한 API 들이 나오는군요

**Comment by mhyeon-lee** [comment]
마크 인터페이스를 도입하게 되면 이 논의를 진행할 필요가 없겟군요

**Comment by gyuwon** [comment]
@mhyeon-lee 표식 인터페이스를 도입해도 `Iterable`은 고려해야 하겠네요.
