### ISSUE TITLE
MessageSerializer 에 #type mapping 등록 지원

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#53]
MessageSerializer 에서 deserialize 시 `#type` 의 값을 원하는 타입으로 deserialize 하도록 매핑을 등록할 수 있으면 좋을거 같습니다.

aaa 애플리케이션에서 `io.aaa.TitleChanged` 타입의 메시지를 발행하면 아래와 같은 형식의 json 메시지가 발행됩니다.

``` json
{
    "#type": "io.aaa.TitleChanged"
}
```

bbb 애플리케이션에서 이 메시지를 받아서 deserialize 할때, aaa 로 부터 해당 이벤트 클래스들을 import 했으면 자연스럽게 deserialize 할 수 있지만, 그렇지 못할 경우에는 bbb 애플리케이션 자체적으로 deserialize할 event 클래스를 만들어야 합니다.

mapping 을 등록할 수 있도록 지원하면, `#type` 이 `io.aaa.TitleChanged` 일 경우 `io.bbb.TitleChanged` 로 deserialize 하도록 등록해서 사용할 수 있을거 같습니다.

**Comment by jaceshim** [comment]
좋은 아이디어 같아요~
하지만 ES관점에서 이벤트 객체의 ownership은 발행 도메인에 있고 이를 제공할 의무가 있다고 봅니다.
예전에 논의 됐던 이벤트 객체를 ES관점에 국한 시키지 않고 Event Driven구조에서의 Message 관점까지 확대 할지 여부가 다시 한번 수면으로 떠오르는것 같아요...
전 사실 이벤트객체가 직렬화된 메세지는 ES관점에서만 해석 되는게 좋을것 같아요~
이유는 일반적인 Event Driven구조하에 발행된 Message와 ES를 통해서 발행된 Message가 동일 Queue에 섞일 여지는 거의 없다고 생각되며 분리된 Queue를 각기 다른 방식으로 처리한다면 Axon처럼 이벤트 헤더 정보를 두는게 더 사용상 편리 할거라 생각합니다.

**Comment by gyuwon** [comment]
@jaceshim 님의 속내는 좋은 아이디어 같지는 않다는거? ㅋㅋ #이간질

**Comment by mhyeon-lee** [comment]
@jaceshim 님이 다시 열어주실때까지 이 이슈는 닫겠습니다  #시무룩

**Comment by jaceshim** [comment]
😱😱😱😱😱😱
