### ISSUE TITLE
Custom Exception Handler 제안

### ISSUE THREAD

**Issue by LeeKyoungIl** [loom/loom-java#57]
loom-core 에서 발생하는 Exception을 특성별로 Custom Exception Handler를 만들까 합니다.

* Exception 메시지는 static 상수로 관리함 (properties)
* LoomException 추상클래스 생성
* Exception 발생시  loom{종류별}Exception을 발생시킴 
* Exception 메시지는 Exception store를 마련해서(로칼) 한곳에 저장 했으면 좋겠음 (file,logback 혹은 hsqldb)
* Exception 스토어에서는 주기적으로 외부 Exception Message store에 Push 할수 있도록 개발 (Quartz)
* Exception 스토어는(외부) 유저가 설정할수 있도록 interface를 제공함 
* Exception 스토어를 만든다면 Exception Model 구조정의 

의견 부탁 드립니다. 일단 Exception  Handler가 필요하다 라고 정도만 의견이 조율되면 작업 시작해 볼께요. 
나머지 세세한 사항은 작업하면서 계속 논의 하는걸로 했음 합니다.

**Comment by jaceshim** [comment]
loom이 좀 더 다양한 환경과 구조에 적용될때 ExceptionHandler는 유용할듯 합니다.👍
하지만 현재 초기 시점에 ExceptionHandler는 loom이 가져가야 목적에 조금 벗어나지 않았나 생각됩니다.

**Comment by jaceshim** [comment]
현재 시점에선 loom에서 발행하는 Exception을 좀 더 다루기 쉽도록 추상화 하는거에 촛점을 맞추는게 좋을것 같습니다

**Comment by LeeKyoungIl** [comment]
@jaceshim  네 좋습니다. 일단 추상화부터 시작해보는걸로 생각하고 있긴 했습니다.

**Comment by gyuwon** [comment]
@LeeKyoungIl @jaceshim 저는 추상화 필요성이 프로그래머의 의도에 의해 만들어지는(invented) 것이 아니라 반복적인 디자인 정제 과정에서 발견되는(discovered) 것이라고 생각합니다. 전자의 경우 사용되지 않거나 과도하게 디자인을 복잡하게 하는 추상화가 만들어질 가능성이 높습니다. 저는 아직 지금까지 도출된 이슈들과 작성된 코드를 기준으로 무엇을 위해 예외를 추상화 해야하는 지 발견하지 못했습니다. 누가 저에게 설명해주실 수 있을까요?

**Comment by jaceshim** [comment]
@gyuwon
말씀대로 추상화는 의도하기 보단 전개과정에서 발견되는 것이 맞습니다. 현 시점에서 추상화를 논하는게 맞지 않을것 같구요~ 구현이 전개되는 과정에 다시 한번 논의 해보는게 좋을것 같아요~
