### ISSUE TITLE
프로젝트 방향성 논의

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#6]
프로젝트 방향성에 대한 논의를 합니다.

* loom-1.0.0 

1. 구현 범위 (인터페이스 && core)
    - domain(aggregate) model
    - event-store
    - event-emitter
    - infrastructures
    - etc..

2. 지원 범위
    - 저장소 : RDBMS, Redis, MongoDB 등등....
    - MessageQueue: Kafka, RabbitMQ 등등...
    - 프레임워크 : Spring Boot

우선 생각나는것만 적어봤습니다.
다양한 의견과 생각들이 있을거 같아 각자가 생각하고 있는 모습과 방향성에 대해 이야기하고 정하면 좋을거 같습니다.

**Comment by jaceshim** [comment]
이벤트 소싱이랑 cqrs 구현체의 식별을 상속(구현) 형태로 가져갈지 annotaion기반으로 가져갈지도 논의 하면 좋을것 같습니다

**Comment by mhyeon-lee** [comment]
시작은 상속(구현) 형태로 가고 개선 버전으로 annotation 을 지원하는건 어떨까 합니다.

**Comment by gyuwon** [comment]
저도 기본적인 OOP 활용이 먼저였으면 좋겠습니다.

**Comment by mhyeon-lee** [comment]
우선 간단한 AggregateRoot, DomainEvent, EventStore 인터페이스와 테스트를 만들어 볼까 합니다.

**Comment by mhyeon-lee** [comment]
식별자 타입에 대한 논의 입니다.
https://github.com/loom/loom-core/issues/13
