### ISSUE TITLE
JacksonSerialize nested 속성에서 $type 제거

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#60]
현재 JacksonSerializer 로 serialize 하면 json 에 nested 된 속성에도 $type 이 붙는거 같습니다.

nested 속성에는 없어도 될거 같습니다.

**Comment by gyuwon** [comment]
어떤 방법이 있을까요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
관련한 옵션이 있는지 잠깐 살펴봤는데 보이지 않는군요.
우선은 2가지 방안이 떠오릅니다.

1. mark interface 를 두고 `useForType` 에 해당 mark interface 만 허용 #49 
    - nested 속성에 mark interface 가 있으면 $type 이  포함될 수 있겠군요

2. TypeResolverBuilder 를 deserialize 에만 적용하고, serialize 시에는 직접 $type 을 추가해주는 방법
    - 원하는대로 동작하는지 테스트는 필요해보입니다.

**Comment by gyuwon** [comment]
저는 1번이 더 나아 보이네요. 메시지가 또 다른 메시지를 속성으로 갖는 구조는 바람직하지 않고 설사 바람직하지 않은 구조로 인해 `$type`이 기록되어도 별 문제가 되지는 않을 것 같고요.

**Comment by mhyeon-lee** [comment]
@jwChung @jaceshim @LeeKyoungIl 
관련해서 의견이 있거나 다른 더 좋은 방법이 있으시면 의견주시면 감사하겠습니다.

**Comment by mhyeon-lee** [comment]
우선 marker interface 로 진행합니다 이견 있으시면 다시 열어주시면 됩니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 이 이슈는 아직 처리되지 않은 것 같습니다.

**Comment by gyuwon** [comment]
이 이슈를 처리하던 중 의견이 달라졌습니다. 속성 형식 기록 여부를 프레임워크가 결정하는 것이 바람직하지 않다는 것인데요. 경우에 따라 메시지의 속성 형식이 추상 클래스이거나 속성 형식을 상속받는 클래스가 설정될 수 있기 때문입니다. 또한 컬렉션 형식의 속성에 담긴 요소의 형식이 서로 다를 수도 있고요. 이 이슈는 `JacksonMessageSerializer`를 사용하는 경우에 한정되기 때문에 메시지 설계자가 `@JsonTypeInfo(use = JsonTypeInfo.Id.NONE)`를 통해 직접 제어하는 것이 어떨까 싶습니다.

**Comment by mhyeon-lee** [comment]
@gyuwon 
```
경우에 따라 메시지의 속성 형식이 추상 클래스이거나 속성 형식을 상속받는 클래스가 설정될 수 있기 때문입니다. 
```
속성 형식은 실제 구현 클래스 로 결정되는 걸로 알고 있는데, 정확하게 어떤 케이스를 말씀하신 건가요? 

---

자문 자답입니다.
직렬화시에는 문제가 없지만 역직렬화시에는 문제가 되겠군요

**Comment by mhyeon-lee** [comment]
결국 메시지의 속성 형식이 인터페이스/추상 클래스일때 역직렬화가 가능하려면 json 에 속성 형식 데이터를 필요로 합니다. 속성 형식 기록 여부를 프레임워크가 처리해줄 것인지 개발자에게 맡길지는 다른 이슈로 논의해보는게 좋겠군요.

**Comment by gyuwon** [comment]
@mhyeon-lee 메시지 속성 설계에 상속을 사용하는 것이 바람직하다고 생각하진 않지만 문제를 남기는 것은 위험할 것 같아요.

**Comment by mhyeon-lee** [comment]
@gyuwon 네 말씀하신 의도를 이제 파악했습니다.  동의합니다 

그럼 `$type` 을 자동으로 붙이지 않을 속성을 정의해야겠군요

우선은 primitive, Enum 정도가 생각나네요
