### ISSUE TITLE
JacksonSerialize 의 $type 기록 여부 결정의 책임 논의

### ISSUE THREAD

**Issue by mhyeon-lee** [loom/loom-java#62]
https://github.com/loom/loom-core/issues/60#issuecomment-314450320 
@gyuwon 님께서 속성 기록 책임을 프레임워크가 가질게 아니라 개발자에게 위임하는게 어떨까 하는 의견을 주셨습니다.

저는 오히려 프레임워크에서 해줘야 할거 같다는 생각입니다.
Message 의 내부 속성을 구현클래스가 아닌 타입으로 정의할 경우에는 역직렬화를 위해 타입 값을 필요로 합니다.
하지만 이 역할을 개발자에게 맡기면 누락시키기 쉬운 부분입니다.
따라서 프레임워크에서 정의된 속성 타입과 실제 값 타입이 일치하지 않다면 직렬화시 자동으로 $type 을 기록해주는 방식으로 지원해주는게 어떨까 합니다.

다른 분들도 의견 부탁드립니다.

**Comment by jaceshim** [comment]
저도 이 부분은 프레임웤에서 강제해줘야할 사항이라고 봅니다. 지나친 강제는 유연성에 걸림돌이 되지만 런 부분이 프레임웤을 사용하는 사용자에게 줄 수  편리성이 아닐까  생각해봅니다

**Comment by jaceshim** [comment]
사용자 정의 type속성을 지원하고 미 설정시 기본 type석성자를 사용하는것도 하나의 방법일거라 보는데 혹시 이미 발행된 메세지와 type변경 후 발행된 메세지 직렬화시 문제의 소지가 있을것 같아 만약 사용자 정의 type을 지원하는경우 이에 대한 고려도 필요할거라 봅니다

**Comment by gyuwon** [comment]
오해가 있는데요. 제가 말씀드린 것은 개발자에게 `$type`을 기록할 책임을 주는 것이 아니라 `$type`을 기록하지 않을 선택권을 주는 것입니다.

> 이 이슈를 처리하던 중 의견이 달라졌습니다. 속성 형식 기록 여부를 프레임워크가 결정하는 것이 바람직하지 않다는 것인데요. 경우에 따라 메시지의 속성 형식이 추상 클래스이거나 속성 형식을 상속받는 클래스가 설정될 수 있기 때문입니다. 또한 컬렉션 형식의 속성에 담긴 요소의 형식이 서로 다를 수도 있고요. 이 이슈는 JacksonMessageSerializer를 사용하는 경우에 한정되기 때문에 메시지 설계자가 @JsonTypeInfo(use = JsonTypeInfo.Id.NONE)를 통해 직접 제어하는 것이 어떨까 싶습니다.

**Comment by mhyeon-lee** [comment]
`JsonTypeInfo.Id.NONE` 였군요 제가 잘못 이해했었네요

@gyuwon 그럼 JacksonMessageSerializer 에서 기본적으로는 `$type` 을 기록하는데,  `@JsonTypeInfo` 어노테이션이 있는 클래스는 해당 어노테이션 설정에 맡긴다는 의견이신거죠?

**Comment by gyuwon** [comment]
@mhyeon-lee 맞습니다. :-)

**Comment by mhyeon-lee** [comment]
`@JsonTypeInfo` 어노테이션이 있는 클래스는 `$type` 기록 여부를 어노테이션 설정에 맡긴다는 걸로 결정하고 이 이슈는 닫습니다.
