### ISSUE TITLE
프로젝트 아이콘 제작

### ISSUE THREAD

**Issue by gyuwon** [loom/loom-java#7]
심플하면서도 화려한 아이콘 제작을 누군가에게 구걸합니다.

**Comment by jwChung** [comment]
아래 아이콘 느낌 괜찮네요. 참고하시라고 링크 올려 둡니다.
 
https://thenounproject.com/term/weave/196959/

**Comment by chulhyuncho** [comment]
무료인지는 모르겠으나... 

https://kr.pinterest.com/search/pins/?q=icons&rs=typed&term_meta[]=icons%7Ctyped
